// Code generated by rig-tools-gen --category=geospace; DO NOT EDIT.

//! Generated tools grouped by URL host `earthquake`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRecentEarthquakesArgs {
    #[serde(default)]
    pub min_magnitude: Option<f64>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetRecentEarthquakesTool {
    base: ToolBase,
}

impl GetRecentEarthquakesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRecentEarthquakesTool {
    const NAME: &'static str = "get_recent_earthquakes";
    type Args = GetRecentEarthquakesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get recent earthquake data worldwide. Returns magnitude, location, time, depth, tsunami potential, and alert level. Use when the user asks about recent earthquakes, seismic activity, or tremors in a region.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "min_magnitude": { "type": "number", "description": "Minimum magnitude filter. Examples: 2.5, 4.5, 6.0. Default is 2.5." },
                "limit": { "type": "integer", "description": "Number of results. Default is 10." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude={min_magnitude}&limit={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(10)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetEarthquakesByRegionArgs {
    pub min_latitude: f64,
    pub max_latitude: f64,
    pub min_longitude: f64,
    pub max_longitude: f64,
    #[serde(default)]
    pub min_magnitude: Option<f64>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetEarthquakesByRegionTool {
    base: ToolBase,
}

impl GetEarthquakesByRegionTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetEarthquakesByRegionTool {
    const NAME: &'static str = "get_earthquakes_by_region";
    type Args = GetEarthquakesByRegionArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get earthquakes within a specific geographic bounding box. Returns magnitude, location, time, depth, and alert level. Use when the user asks about earthquakes in a specific country, region, or area (e.g. \"Indonesia\", \"Japan\", \"California\").".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "min_latitude": { "type": "number", "description": "Southern boundary (e.g. -11 for Indonesia)." },
                "max_latitude": { "type": "number", "description": "Northern boundary (e.g. 6 for Indonesia)." },
                "min_longitude": { "type": "number", "description": "Western boundary (e.g. 95 for Indonesia)." },
                "max_longitude": { "type": "number", "description": "Eastern boundary (e.g. 141 for Indonesia)." },
                "min_magnitude": { "type": "number", "description": "Minimum magnitude filter. Default is 2.5." },
                "limit": { "type": "integer", "description": "Number of results. Default is 10." },
            },
            "required": [
                "min_latitude",
                "max_latitude",
                "min_longitude",
                "max_longitude",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude={min_magnitude}&minlatitude={min_latitude}&maxlatitude={max_latitude}&minlongitude={min_longitude}&maxlongitude={max_longitude}&limit={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(10)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSignificantEarthquakesArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetSignificantEarthquakesTool {
    base: ToolBase,
}

impl GetSignificantEarthquakesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSignificantEarthquakesTool {
    const NAME: &'static str = "get_significant_earthquakes";
    type Args = GetSignificantEarthquakesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get significant earthquakes from the past month worldwide. These are earthquakes that had impact (felt by many people, caused damage, or were large magnitude). Returns magnitude, location, time, tsunami flag, and alert level. Use when the user asks about major or significant recent earthquakes.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.geojson",
            headers: None,
            defaults: None,
        }, map).await
    }
}
