// Code generated by rig-tools-gen --category=geospace; DO NOT EDIT.

//! Generated tools grouped by URL host `opensky_network`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetFlightsInAreaArgs {
    pub min_latitude: f64,
    pub max_latitude: f64,
    pub min_longitude: f64,
    pub max_longitude: f64,
}

#[derive(Debug, Clone, Default)]
pub struct GetFlightsInAreaTool {
    base: ToolBase,
}

impl GetFlightsInAreaTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetFlightsInAreaTool {
    const NAME: &'static str = "get_flights_in_area";
    type Args = GetFlightsInAreaArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get real-time aircraft positions within a geographic bounding box. Returns callsign, origin country, longitude, latitude, altitude, velocity, and heading. Use when the user asks about flights currently in a specific area or region.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "min_latitude": { "type": "number", "description": "Southern boundary (e.g. -8 for Indonesia)." },
                "max_latitude": { "type": "number", "description": "Northern boundary (e.g. 6 for Indonesia)." },
                "min_longitude": { "type": "number", "description": "Western boundary (e.g. 95 for Indonesia)." },
                "max_longitude": { "type": "number", "description": "Eastern boundary (e.g. 141 for Indonesia)." },
            },
            "required": [
                "min_latitude",
                "max_latitude",
                "min_longitude",
                "max_longitude",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://opensky-network.org/api/states/all?lamin={min_latitude}&lamax={max_latitude}&lomin={min_longitude}&lomax={max_longitude}",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRecentFlightsArgs {
    pub begin: i64,
    pub end: i64,
}

#[derive(Debug, Clone, Default)]
pub struct GetRecentFlightsTool {
    base: ToolBase,
}

impl GetRecentFlightsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRecentFlightsTool {
    const NAME: &'static str = "get_recent_flights";
    type Args = GetRecentFlightsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get flights that arrived or departed in a time range. Returns callsign, departure airport, arrival airport, and timestamps. Use when the user asks about recent flight activity. Provide begin and end as Unix timestamps.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "begin": { "type": "integer", "description": "Start of time range as Unix timestamp. Example: 1749000000 for a specific time." },
                "end": { "type": "integer", "description": "End of time range as Unix timestamp. Example: 1749086400 for a specific time." },
            },
            "required": [
                "begin",
                "end",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://opensky-network.org/api/flights/all?begin={begin}&end={end}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
