// Code generated by rig-tools-gen --category=geospace; DO NOT EDIT.

//! Generated tools grouped by URL host `spacexdata`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSpacexLatestLaunchArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetSpacexLatestLaunchTool {
    base: ToolBase,
}

impl GetSpacexLatestLaunchTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSpacexLatestLaunchTool {
    const NAME: &'static str = "get_spacex_latest_launch";
    type Args = GetSpacexLatestLaunchArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the latest SpaceX launch data. Returns rocket name, launch date, success status, payload details, crew info, launch site, and webcast link. Use when the user asks about the latest SpaceX launch or rocket.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.spacexdata.com/v5/launches/latest",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSpacexRocketsArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetSpacexRocketsTool {
    base: ToolBase,
}

impl GetSpacexRocketsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSpacexRocketsTool {
    const NAME: &'static str = "get_spacex_rockets";
    type Args = GetSpacexRocketsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get all SpaceX rockets including Falcon 9, Falcon Heavy, and Starship. Returns rocket name, type, active status, cost per launch, success rate, height, mass, and description.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.spacexdata.com/v4/rockets",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSpacexUpcomingLaunchesArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetSpacexUpcomingLaunchesTool {
    base: ToolBase,
}

impl GetSpacexUpcomingLaunchesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSpacexUpcomingLaunchesTool {
    const NAME: &'static str = "get_spacex_upcoming_launches";
    type Args = GetSpacexUpcomingLaunchesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get upcoming SpaceX launches. Returns launch date, rocket, payload, launch site, and details. Use when the user asks about the next SpaceX launch.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.spacexdata.com/v5/launches/upcoming",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
