// Code generated by rig-tools-gen --category=browser; DO NOT EDIT.

//! Generated tools grouped by URL host `cloudflare`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct BrowserMarkdownExtractArgs {
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub html: Option<String>,
    #[serde(default)]
    pub rejectRequestPattern: Option<serde_json::Value>,
    #[serde(default)]
    pub gotoOptions: Option<serde_json::Value>,
    #[serde(default)]
    pub userAgent: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct BrowserMarkdownExtractTool {
    base: ToolBase,
}

impl BrowserMarkdownExtractTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for BrowserMarkdownExtractTool {
    const NAME: &'static str = "browser_markdown_extract";
    type Args = BrowserMarkdownExtractArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Extract the readable content of any public webpage as Markdown using Cloudflare Browser Run's /markdown quick action. Use when the user asks to read, fetch, summarize, scrape, or quote a URL — including JavaScript-heavy pages, SPAs, and sites that block simple HTTP fetches. Returns the page rendered by a real browser, with scripts and styling stripped. Provide either `url` OR `html`, and optionally `rejectRequestPattern`, `gotoOptions` (JSON object string, e.g. '{\"waitUntil\":\"networkidle0\"}'), and `userAgent`.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "url": { "type": "string", "description": "Absolute URL of the page to render. Provide this OR `html`. Examples: \"https://example.com\", \"https://blog.cloudflare.com/...\". Omit when sending raw HTML." },
                "html": { "type": "string", "description": "Raw HTML string to convert. Provide this OR `url`. Example: \"<div>Hello World</div>\"." },
                "rejectRequestPattern": { "type": "array", "description": "Optional list of regex patterns for resources to skip while loading the page (e.g. CSS, tracking). Pass a JSON array string. Example: '[\"/^.*\\\\.(css)/\"]'." },
                "gotoOptions": { "type": "object", "description": "Optional Puppeteer-style load options as a JSON object string. Example: '{\"waitUntil\":\"networkidle0\"}' for JavaScript-heavy pages / SPAs." },
                "userAgent": { "type": "string", "description": "Custom User-Agent string. Note: does not bypass bot protection." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "POST",
            url_tpl: "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/browser-rendering/markdown",
            headers: Some(Box::new([
                ("Authorization", "Bearer $CLOUDFLARE_API_TOKEN_BROWSER_RENDERING"),
                ("Content-Type", "application/json"),
            ])),
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct BrowserContentExtractArgs {
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub html: Option<String>,
    #[serde(default)]
    pub rejectResourceTypes: Option<serde_json::Value>,
    #[serde(default)]
    pub rejectRequestPattern: Option<serde_json::Value>,
    #[serde(default)]
    pub userAgent: Option<String>,
    #[serde(default)]
    pub gotoOptions: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Default)]
pub struct BrowserContentExtractTool {
    base: ToolBase,
}

impl BrowserContentExtractTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for BrowserContentExtractTool {
    const NAME: &'static str = "browser_content_extract";
    type Args = BrowserContentExtractArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Fetch the fully rendered inner HTML (including body content) of a webpage using Cloudflare Browser Run's /content endpoint. Unlike a simple curl/wget, this runs JavaScript and captures the post-render DOM. Provide `url` or `html`, and optionally `rejectResourceTypes` (JSON array of resource types to block), `rejectRequestPattern` (JSON array of regex patterns), `setExtraHTTPHeaders` (JSON object), `userAgent`, or `gotoOptions` (JSON object e.g. {\"waitUntil\":\"networkidle0\"}).".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "url": { "type": "string", "description": "Absolute URL of the page to render. Provide this OR `html`." },
                "html": { "type": "string", "description": "Raw HTML string to render. Provide this OR `url`." },
                "rejectResourceTypes": { "type": "array", "description": "JSON array of resource types to block (e.g. [\"image\",\"stylesheet\",\"font\"])." },
                "rejectRequestPattern": { "type": "array", "description": "JSON array of regex patterns for resources to skip (e.g. [\"/^.*\\\\.(css)/\"])." },
                "userAgent": { "type": "string", "description": "Custom User-Agent string. Not for bypassing bot protection." },
                "gotoOptions": { "type": "object", "description": "JSON object for Puppeteer-style load options. Example: {\"waitUntil\":\"networkidle0\"}." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "POST",
            url_tpl: "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/browser-rendering/content",
            headers: Some(Box::new([
                ("Authorization", "Bearer $CLOUDFLARE_API_TOKEN_BROWSER_RENDERING"),
                ("Content-Type", "application/json"),
            ])),
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct BrowserJsonExtractArgs {
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub html: Option<String>,
    #[serde(default)]
    pub prompt: Option<String>,
    #[serde(default)]
    pub response_format: Option<serde_json::Value>,
    #[serde(default)]
    pub userAgent: Option<String>,
    #[serde(default)]
    pub gotoOptions: Option<serde_json::Value>,
    #[serde(default)]
    pub custom_ai: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Default)]
pub struct BrowserJsonExtractTool {
    base: ToolBase,
}

impl BrowserJsonExtractTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for BrowserJsonExtractTool {
    const NAME: &'static str = "browser_json_extract";
    type Args = BrowserJsonExtractArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Extract structured JSON data from a webpage using Cloudflare Browser Run's AI-powered /json endpoint. Uses Workers AI (Llama 3.3 70B) by default. Provide `url` or `html`, AND at least one of `prompt` (natural-language description of what to extract) or `response_format` (JSON schema object). Optionally provide `userAgent`, `gotoOptions`, and `custom_ai` (JSON array of model overrides, e.g. [{\"model\":\"anthropic/claude-sonnet-4-20250514\",\"authorization\":\"Bearer $KEY\"}]).".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "url": { "type": "string", "description": "Absolute URL of the page to extract data from." },
                "html": { "type": "string", "description": "Raw HTML string to extract data from." },
                "prompt": { "type": "string", "description": "Natural-language description of what to extract. Example: \"Get me the list of AI products with their names and links\"." },
                "response_format": { "type": "object", "description": "JSON schema object defining the expected output structure. Example: {\"type\":\"json_schema\",\"schema\":{\"type\":\"object\",\"properties\":{\"items\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"}}}}}}}." },
                "userAgent": { "type": "string", "description": "Custom User-Agent string." },
                "gotoOptions": { "type": "object", "description": "JSON object for load options. Example: {\"waitUntil\":\"networkidle0\"}." },
                "custom_ai": { "type": "array", "description": "JSON array of custom AI model configs for BYO API key. Each item: {\"model\":\"provider/model\",\"authorization\":\"Bearer $KEY\"}." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "POST",
            url_tpl: "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/browser-rendering/json",
            headers: Some(Box::new([
                ("Authorization", "Bearer $CLOUDFLARE_API_TOKEN_BROWSER_RENDERING"),
                ("Content-Type", "application/json"),
            ])),
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct BrowserLinksExtractArgs {
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub html: Option<String>,
    #[serde(default)]
    pub visibleLinksOnly: Option<bool>,
    #[serde(default)]
    pub excludeExternalLinks: Option<bool>,
    #[serde(default)]
    pub userAgent: Option<String>,
    #[serde(default)]
    pub gotoOptions: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Default)]
pub struct BrowserLinksExtractTool {
    base: ToolBase,
}

impl BrowserLinksExtractTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for BrowserLinksExtractTool {
    const NAME: &'static str = "browser_links_extract";
    type Args = BrowserLinksExtractArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Extract all links from a webpage using Cloudflare Browser Run's /links endpoint. Returns a JSON array of absolute URLs. Provide `url` or `html`, and optionally `visibleLinksOnly` (boolean), `excludeExternalLinks` (boolean), `userAgent`, or `gotoOptions`.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "url": { "type": "string", "description": "Absolute URL of the page to extract links from." },
                "html": { "type": "string", "description": "Raw HTML string to extract links from." },
                "visibleLinksOnly": { "type": "boolean", "description": "Only return links visible on the rendered page (default false)." },
                "excludeExternalLinks": { "type": "boolean", "description": "Exclude links to external domains (default false)." },
                "userAgent": { "type": "string", "description": "Custom User-Agent string." },
                "gotoOptions": { "type": "object", "description": "JSON object for load options. Example: {\"waitUntil\":\"networkidle0\"}." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "POST",
            url_tpl: "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/browser-rendering/links",
            headers: Some(Box::new([
                ("Authorization", "Bearer $CLOUDFLARE_API_TOKEN_BROWSER_RENDERING"),
                ("Content-Type", "application/json"),
            ])),
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct BrowserScrapeElementsArgs {
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub elements: Option<serde_json::Value>,
    #[serde(default)]
    pub userAgent: Option<String>,
    #[serde(default)]
    pub gotoOptions: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Default)]
pub struct BrowserScrapeElementsTool {
    base: ToolBase,
}

impl BrowserScrapeElementsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for BrowserScrapeElementsTool {
    const NAME: &'static str = "browser_scrape_elements";
    type Args = BrowserScrapeElementsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Scrape specific HTML elements from a webpage using Cloudflare Browser Run's /scrape endpoint. Provide `url` or `elements` (JSON array of {selector:\"css-selector\", ...}), and optionally `userAgent` or `gotoOptions`. Returns structured data for each matched element including text, HTML, attributes, and position/dimensions.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "url": { "type": "string", "description": "Absolute URL of the page to scrape. Provide this OR `elements`." },
                "elements": { "type": "array", "description": "JSON array of objects describing elements to extract. Each object must have a \"selector\" string. Example: [{\"selector\":\"h1\"},{\"selector\":\"a\"}] to scrape all h1 and anchor elements." },
                "userAgent": { "type": "string", "description": "Custom User-Agent string." },
                "gotoOptions": { "type": "object", "description": "JSON object for load options. Example: {\"waitUntil\":\"networkidle0\"}." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "POST",
            url_tpl: "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/browser-rendering/scrape",
            headers: Some(Box::new([
                ("Authorization", "Bearer $CLOUDFLARE_API_TOKEN_BROWSER_RENDERING"),
                ("Content-Type", "application/json"),
            ])),
            defaults: None,
        }, map).await
    }
}
