// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `date`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetPublicHolidaysArgs {
    pub year: i64,
    pub country_code: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetPublicHolidaysTool {
    base: ToolBase,
}

impl GetPublicHolidaysTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetPublicHolidaysTool {
    const NAME: &'static str = "get_public_holidays";
    type Args = GetPublicHolidaysArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the list of public holidays for a specific country and year. Use when the user asks about holidays or whether a date is a holiday.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "year": { "type": "integer", "description": "The year. Examples: 2024, 2025, 2026." },
                "country_code": { "type": "string", "description": "Two-letter ISO 3166-1 country code. Examples: US, GB, DE, ID, JP, FR." },
            },
            "required": [
                "year",
                "country_code",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://date.nager.at/api/v3/PublicHolidays/{year}/{country_code}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
