// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `dictionaryapi`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DefineWordArgs {
    pub word: String,
}

#[derive(Debug, Clone, Default)]
pub struct DefineWordTool {
    base: ToolBase,
}

impl DefineWordTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for DefineWordTool {
    const NAME: &'static str = "define_word";
    type Args = DefineWordArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Look up the definition, pronunciation, part of speech, synonyms, and usage examples for an English word. Use when the user asks what a word means or wants synonyms.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "word": { "type": "string", "description": "The English word to define." },
            },
            "required": [
                "word",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.dictionaryapi.dev/api/v2/entries/en/{word}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
