// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `fruityvice`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetFruitInfoArgs {
    pub fruit_name: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetFruitInfoTool {
    base: ToolBase,
}

impl GetFruitInfoTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetFruitInfoTool {
    const NAME: &'static str = "get_fruit_info";
    type Args = GetFruitInfoArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get nutritional information about a specific fruit including calories, fat, sugar, carbohydrates, protein, and botanical classification (family, order, genus). Use when the user asks about fruit nutrition, calories in a fruit, or fruit facts.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "fruit_name": { "type": "string", "description": "Name of the fruit. Examples: \"banana\", \"apple\", \"mango\", \"strawberry\", \"orange\"." },
            },
            "required": [
                "fruit_name",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.fruityvice.com/api/fruit/{fruit_name}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetAllFruitsArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetAllFruitsTool {
    base: ToolBase,
}

impl GetAllFruitsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetAllFruitsTool {
    const NAME: &'static str = "get_all_fruits";
    type Args = GetAllFruitsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a list of all available fruits with their nutritional data. Use when the user asks what fruits are available or wants to compare fruit nutrition.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.fruityvice.com/api/fruit/all",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
