// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `github`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchGithubReposArgs {
    pub query: String,
    #[serde(default)]
    pub sort: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchGithubReposTool {
    base: ToolBase,
}

impl SearchGithubReposTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchGithubReposTool {
    const NAME: &'static str = "search_github_repos";
    type Args = SearchGithubReposArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for GitHub repositories by keyword. Returns repo name, description, stars, forks, language, and owner. Use when the user asks to find open-source projects, libraries, or tools on GitHub.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search keywords. Examples: \"nextjs\", \"machine learning python\", \"react ui library\"." },
                "sort": { "type": "string", "description": "Sort by. Options: \"stars\" (most starred), \"forks\", \"updated\". Default is \"stars\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.github.com/search/repositories?q={query}&sort={sort}&per_page={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetGithubUserArgs {
    pub username: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetGithubUserTool {
    base: ToolBase,
}

impl GetGithubUserTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetGithubUserTool {
    const NAME: &'static str = "get_github_user";
    type Args = GetGithubUserArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get information about a GitHub user or organization. Returns name, bio, location, company, public repos count, followers, following, and blog URL. Use when the user asks about a GitHub profile or developer.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "username": { "type": "string", "description": "GitHub username. Examples: \"torvalds\", \"gaearon\", \"sindresorhus\"." },
            },
            "required": [
                "username",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.github.com/users/{username}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetGithubRepoArgs {
    pub owner: String,
    pub repo: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetGithubRepoTool {
    base: ToolBase,
}

impl GetGithubRepoTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetGithubRepoTool {
    const NAME: &'static str = "get_github_repo";
    type Args = GetGithubRepoArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a GitHub repository. Returns description, stars, forks, open issues, language, license, creation date, and last update. Use when the user asks about a specific repository.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "owner": { "type": "string", "description": "Repository owner (user or org). Examples: \"facebook\", \"vercel\", \"microsoft\"." },
                "repo": { "type": "string", "description": "Repository name. Examples: \"react\", \"next.js\", \"typescript\"." },
            },
            "required": [
                "owner",
                "repo",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.github.com/repos/{owner}/{repo}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
