// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `mathjs`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CalculateArgs {
    pub expression: String,
}

#[derive(Debug, Clone, Default)]
pub struct CalculateTool {
    base: ToolBase,
}

impl CalculateTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for CalculateTool {
    const NAME: &'static str = "calculate";
    type Args = CalculateArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Evaluate mathematical expressions and convert units. Supports arithmetic, trigonometry, logarithms, square roots, and unit conversions (km to miles, kg to lb, Celsius to Fahrenheit, etc). Use when the user asks a math question or wants to convert between units.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "expression": { "type": "string", "description": "Math expression. Examples: \"2 + 2 * 3\", \"sqrt(144)\", \"100 km to miles\", \"72 kg to lb\", \"30 celsius to fahrenheit\", \"sin(pi/4)\", \"log(100)\"." },
            },
            "required": [
                "expression",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.mathjs.org/v4/?expr={expression}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
