// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `openalex`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchPapersArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchPapersTool {
    base: ToolBase,
}

impl SearchPapersTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchPapersTool {
    const NAME: &'static str = "search_papers";
    type Args = SearchPapersArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for academic papers by topic or keyword. Returns titles, authors, year, and DOIs. Use when the user asks about research or scholarly articles.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search terms. Examples: \"machine learning\", \"quantum computing\", \"climate change\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 3." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.openalex.org/works?search={query}&per_page={limit}",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(3))])),
                },
                map,
            )
            .await
    }
}
