// Code generated by rig-tools-gen --category=knowledge; DO NOT EDIT.

//! Generated tools grouped by URL host `restcountries`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCountryInfoArgs {
    pub country_name: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetCountryInfoTool {
    base: ToolBase,
}

impl GetCountryInfoTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCountryInfoTool {
    const NAME: &'static str = "get_country_info";
    type Args = GetCountryInfoArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a country including capital city, currencies, languages, population, area, and flag. Use when the user asks about a country's facts.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "country_name": { "type": "string", "description": "Common name of the country. Examples: \"Japan\", \"Indonesia\", \"Brazil\", \"Germany\"." },
            },
            "required": [
                "country_name",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://restcountries.com/v3.1/name/{country_name}?fields=name,capital,currencies,languages,population,flags,region,area",
            headers: None,
            defaults: None,
        }, map).await
    }
}
