// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `jikan`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchAnimeArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchAnimeTool {
    base: ToolBase,
}

impl SearchAnimeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchAnimeTool {
    const NAME: &'static str = "search_anime";
    type Args = SearchAnimeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for anime by title, genre, or keyword. Returns title, score, episodes, status, synopsis, studios, genres, and year. Use when the user asks about an anime series, wants recommendations, or wants to look up anime information.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Anime title or keyword to search for. Examples: \"Naruto\", \"Attack on Titan\", \"One Piece\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.jikan.moe/v4/anime?q={query}&limit={limit}&sfw=true",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(5))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetAnimeDetailArgs {
    pub anime_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetAnimeDetailTool {
    base: ToolBase,
}

impl GetAnimeDetailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetAnimeDetailTool {
    const NAME: &'static str = "get_anime_detail";
    type Args = GetAnimeDetailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a specific anime by its MyAnimeList ID. Returns full synopsis, episodes, score, studios, genres, broadcast info, and more. Use when the user wants detailed info about a specific anime.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "anime_id": { "type": "string", "description": "MyAnimeList anime ID. Example: 20 (Naruto), 16498 (Attack on Titan), 21 (One Piece)." },
            },
            "required": [
                "anime_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.jikan.moe/v4/anime/{anime_id}/full",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTopAnimeArgs {
    #[serde(default)]
    #[serde(rename = "type")]
    pub r#type: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTopAnimeTool {
    base: ToolBase,
}

impl GetTopAnimeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTopAnimeTool {
    const NAME: &'static str = "get_top_anime";
    type Args = GetTopAnimeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the top rated anime of all time or filtered by type. Returns title, score, rank, episodes, and year. Use when the user asks for best anime, top rated anime, or recommendations.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "type": { "type": "string", "description": "Filter by type. Options: tv, movie, ova, special, ona, music. Optional." },
                "limit": { "type": "integer", "description": "Number of results. Default is 10." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.jikan.moe/v4/top/anime?type={type}&limit={limit}",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(10))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSeasonalAnimeArgs {
    pub year: i64,
    pub season: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetSeasonalAnimeTool {
    base: ToolBase,
}

impl GetSeasonalAnimeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSeasonalAnimeTool {
    const NAME: &'static str = "get_seasonal_anime";
    type Args = GetSeasonalAnimeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get anime airing in a specific season and year. Returns currently airing or upcoming anime with their schedule. Use when the user asks about new anime this season or what's airing now.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "year": { "type": "integer", "description": "The year. Examples: 2024, 2025, 2026." },
                "season": { "type": "string", "description": "Season name: winter, spring, summer, or fall." },
                "limit": { "type": "integer", "description": "Number of results. Default is 10." },
            },
            "required": [
                "year",
                "season",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl:
                        "https://api.jikan.moe/v4/seasons/{year}/{season}?limit={limit}&sfw=true",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(10))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchMangaArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchMangaTool {
    base: ToolBase,
}

impl SearchMangaTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchMangaTool {
    const NAME: &'static str = "search_manga";
    type Args = SearchMangaArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for manga by title, genre, or keyword. Returns title, score, chapters, status, synopsis, authors, genres, and year. Use when the user asks about a manga series, wants manga recommendations, or wants to look up manga information.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Manga title or keyword to search for. Examples: \"Berserk\", \"One Piece\", \"Chainsaw Man\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.jikan.moe/v4/manga?q={query}&limit={limit}",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(5))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTopMangaArgs {
    #[serde(default)]
    #[serde(rename = "type")]
    pub r#type: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTopMangaTool {
    base: ToolBase,
}

impl GetTopMangaTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTopMangaTool {
    const NAME: &'static str = "get_top_manga";
    type Args = GetTopMangaArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the top rated manga of all time or filtered by type. Returns title, score, rank, chapters, and year. Use when the user asks for best manga, top rated manga, or recommendations.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "type": { "type": "string", "description": "Filter by type. Options: manga, novels, lightnovels, oneshot, doujin, manhwa, manhua. Optional." },
                "limit": { "type": "integer", "description": "Number of results. Default is 10." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.jikan.moe/v4/top/manga?type={type}&limit={limit}",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(10))])),
                },
                map,
            )
            .await
    }
}
