// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `musicbrainz`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchArtistArgs {
    pub artist_name: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchArtistTool {
    base: ToolBase,
}

impl SearchArtistTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchArtistTool {
    const NAME: &'static str = "search_artist";
    type Args = SearchArtistArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for a music artist or band. Returns name, country, type (person/group), life span (active years), origin city, genres, and aliases. Use when the user asks about a musician, band, or artist.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "artist_name": { "type": "string", "description": "Artist or band name. Examples: \"Coldplay\", \"Taylor Swift\", \"BTS\", \"The Beatles\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "artist_name",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://musicbrainz.org/ws/2/artist/?query=artist:{artist_name}&fmt=json&limit={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchAlbumArgs {
    pub album_name: String,
    #[serde(default)]
    pub artist_name: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchAlbumTool {
    base: ToolBase,
}

impl SearchAlbumTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchAlbumTool {
    const NAME: &'static str = "search_album";
    type Args = SearchAlbumArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for a music album or release. Returns title, artist, release date, type (album/single/EP), and country. Use when the user asks about an album, discography, or release information.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "album_name": { "type": "string", "description": "Album or release title. Examples: \"Thriller\", \"Abbey Road\", \"21\"." },
                "artist_name": { "type": "string", "description": "Artist name to narrow results. Optional but recommended. Examples: \"Michael Jackson\", \"The Beatles\", \"Adele\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "album_name",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://musicbrainz.org/ws/2/release-group/?query=releasegroup:{album_name}+AND+artist:{artist_name}&fmt=json&limit={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}
