// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `openlibrary`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchBooksArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchBooksTool {
    base: ToolBase,
}

impl SearchBooksTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchBooksTool {
    const NAME: &'static str = "search_books";
    type Args = SearchBooksArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for books by title, author, or keyword through Open Library. Returns title, author, ISBN, publication year, and subjects. Use when the user wants to find a book or get reading recommendations.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Book title, author, or keyword. Examples: \"Harry Potter\", \"Stephen King\", \"machine learning\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://openlibrary.org/search.json?q={query}&limit={limit}",
                    headers: None,
                    defaults: Some(Box::new([("limit", serde_json::json!(5))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetBookByIsbnArgs {
    pub isbn: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetBookByIsbnTool {
    base: ToolBase,
}

impl GetBookByIsbnTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetBookByIsbnTool {
    const NAME: &'static str = "get_book_by_isbn";
    type Args = GetBookByIsbnArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a book by its ISBN number. Returns title, author, publisher, publication date, pages, and subjects. Use when the user provides an ISBN.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "isbn": { "type": "string", "description": "10 or 13-digit ISBN. Examples: \"9780545139700\" (Harry Potter), \"9780451524935\" (1984)." },
            },
            "required": [
                "isbn",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://openlibrary.org/isbn/{isbn}.json",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
