// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `pexels`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchPhotosArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchPhotosTool {
    base: ToolBase,
}

impl SearchPhotosTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchPhotosTool {
    const NAME: &'static str = "search_photos";
    type Args = SearchPhotosArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for free stock photos by keyword. Returns photo URLs, photographer credit, dimensions, and description. Use when the user asks to find images or photos of something (nature, cities, animals, etc).".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search keyword. Examples: \"mountain landscape\", \"cat\", \"Jakarta skyline\", \"coffee cup\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.pexels.com/v1/search?query={query}&per_page={limit}",
                    headers: Some(Box::new([(
                        "Authorization",
                        "HBIwjS76OIhXvCEmX019AFLXBBXh2p0VN7qUx4asImUrDjmOKd4J4rUb",
                    )])),
                    defaults: Some(Box::new([("limit", serde_json::json!(5))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchVideosArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchVideosTool {
    base: ToolBase,
}

impl SearchVideosTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchVideosTool {
    const NAME: &'static str = "search_videos";
    type Args = SearchVideosArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for free stock videos by keyword. Returns video URLs, duration, photographer credit, and thumbnails. Use when the user asks to find video footage of something.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search keyword. Examples: \"ocean waves\", \"city timelapse\", \"cooking\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.pexels.com/videos/search?query={query}&per_page={limit}",
                    headers: Some(Box::new([(
                        "Authorization",
                        "HBIwjS76OIhXvCEmX019AFLXBBXh2p0VN7qUx4asImUrDjmOKd4J4rUb",
                    )])),
                    defaults: Some(Box::new([("limit", serde_json::json!(5))])),
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCuratedPhotosArgs {
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCuratedPhotosTool {
    base: ToolBase,
}

impl GetCuratedPhotosTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCuratedPhotosTool {
    const NAME: &'static str = "get_curated_photos";
    type Args = GetCuratedPhotosArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get curated, hand-picked high-quality photos from Pexels editors. Use when the user wants beautiful or trending photos without a specific search.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.pexels.com/v1/curated?per_page={limit}",
                    headers: Some(Box::new([(
                        "Authorization",
                        "HBIwjS76OIhXvCEmX019AFLXBBXh2p0VN7qUx4asImUrDjmOKd4J4rUb",
                    )])),
                    defaults: Some(Box::new([("limit", serde_json::json!(5))])),
                },
                map,
            )
            .await
    }
}
