// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `poetrydb`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchPoemsByTitleArgs {
    pub title: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchPoemsByTitleTool {
    base: ToolBase,
}

impl SearchPoemsByTitleTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchPoemsByTitleTool {
    const NAME: &'static str = "search_poems_by_title";
    type Args = SearchPoemsByTitleArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for poems by title. Returns title, author, lines, and line count. Use when the user asks for a specific poem by name.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "title": { "type": "string", "description": "Poem title. Examples: \"Ozymandias\", \"The Raven\", \"Sonnet 18\"." },
            },
            "required": [
                "title",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://poetrydb.org/title/{title}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchPoemsByAuthorArgs {
    pub author: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchPoemsByAuthorTool {
    base: ToolBase,
}

impl SearchPoemsByAuthorTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchPoemsByAuthorTool {
    const NAME: &'static str = "search_poems_by_author";
    type Args = SearchPoemsByAuthorArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get all poems by a specific author. Returns titles, lines, and line counts. Use when the user asks for poems by an author.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "author": { "type": "string", "description": "Author name. Examples: \"Emily Dickinson\", \"Robert Frost\", \"Shakespeare\"." },
            },
            "required": [
                "author",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://poetrydb.org/author/{author}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRandomPoemArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetRandomPoemTool {
    base: ToolBase,
}

impl GetRandomPoemTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRandomPoemTool {
    const NAME: &'static str = "get_random_poem";
    type Args = GetRandomPoemArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a random poem. Returns title, author, lines, and line count. Use when the user wants poetry inspiration or a random poem.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://poetrydb.org/random",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
