// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `tastedive`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRecommendationsArgs {
    pub query: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetRecommendationsTool {
    base: ToolBase,
}

impl GetRecommendationsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRecommendationsTool {
    const NAME: &'static str = "get_recommendations";
    type Args = GetRecommendationsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get recommendations for movies, TV shows, music, books, games, podcasts, or people based on something the user already likes. Returns similar items with description and YouTube clip when available. Use when the user asks \"if you like X, try Y\" or wants suggestions based on their taste.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Item(s) the user likes, separated by commas. Can prefix with type: \"movie:Inception\", \"music:Coldplay\", \"book:Harry Potter\", \"show:Breaking Bad\", \"game:The Witcher\", \"person:Christopher Nolan\". Examples: \"Inception, Interstellar\", \"music:Radiohead\", \"book:Dune\"." },
                "type": { "type": "string", "description": "Type of recommendations to return. Options: \"movie\", \"show\", \"music\", \"book\", \"game\", \"podcast\", \"person\", \"place\", \"brand\"." },
                "limit": { "type": "integer", "description": "Number of recommendations. Default is 5." },
            },
            "required": [
                "query",
                "type",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://tastedive.com/api/similar?q={query}&type={type}&info=1&limit={limit}&k=1073689-vscode-E8A1084A",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}
