// Code generated by rig-tools-gen --category=entertainment; DO NOT EDIT.

//! Generated tools grouped by URL host `tvmaze`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchTvShowArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchTvShowTool {
    base: ToolBase,
}

impl SearchTvShowTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchTvShowTool {
    const NAME: &'static str = "search_tv_show";
    type Args = SearchTvShowArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for TV shows by name. Returns show name, rating, genres, status, network, premiere date, schedule, and summary. Use when the user asks about a TV show.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "TV show name. Examples: \"Breaking Bad\", \"Stranger Things\", \"The Mandalorian\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.tvmaze.com/search/shows?q={query}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTvShowDetailArgs {
    pub show_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetTvShowDetailTool {
    base: ToolBase,
}

impl GetTvShowDetailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTvShowDetailTool {
    const NAME: &'static str = "get_tv_show_detail";
    type Args = GetTvShowDetailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a TV show by its TVMaze ID including embedded episodes. Returns full show info with all episodes (season, number, name, air date, rating, summary). Use when the user wants detailed info or episode list of a specific show.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "show_id": { "type": "string", "description": "TVMaze show ID. Obtained from search results. Example: 169 (Breaking Bad), 1871 (Mr. Robot), 305 (Game of Thrones)." },
            },
            "required": [
                "show_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.tvmaze.com/shows/{show_id}?embed=episodes",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTvShowSeasonsArgs {
    pub show_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetTvShowSeasonsTool {
    base: ToolBase,
}

impl GetTvShowSeasonsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTvShowSeasonsTool {
    const NAME: &'static str = "get_tv_show_seasons";
    type Args = GetTvShowSeasonsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get all seasons of a TV show by its TVMaze ID. Returns season number, episode count, premiere and end dates, network, and summary. Use when the user wants season overview.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "show_id": { "type": "string", "description": "TVMaze show ID." },
            },
            "required": [
                "show_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.tvmaze.com/shows/{show_id}/seasons",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTvScheduleArgs {
    #[serde(default)]
    pub country: Option<String>,
    #[serde(default)]
    pub date: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTvScheduleTool {
    base: ToolBase,
}

impl GetTvScheduleTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTvScheduleTool {
    const NAME: &'static str = "get_tv_schedule";
    type Args = GetTvScheduleArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the TV schedule for a specific date and country. Returns episode name, show, air time, network, and summary. Use when the user asks what's on TV today or wants to check a show's airing schedule.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "country": { "type": "string", "description": "Two-letter country code. Examples: \"US\", \"GB\", \"JP\". Default is \"US\"." },
                "date": { "type": "string", "description": "Date in YYYY-MM-DD format. Example: \"2026-06-05\". Default is today." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.tvmaze.com/schedule?country={country}&date={date}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
