//! Civitai image generation — Generator panel ops (both transports).
//!
//! Pure layer — `reqwest` + the `civitai` client crate only, no tauri/axum:
//! BOTH transports (Tauri commands in `commands.rs`, Axum routes in `web.rs`)
//! call these same fns. Identity (`user_id`) is resolved at the transport
//! edge and passed in — the frontend never sends it.
//!
//! Credential model: the Civitai API key is product-baked in
//! `kawai-vault/constants` (`civitai::get_civitai()`, generated by the
//! vault's gen crate). Empty getter = generation unconfigured.
//!
//! Flow: `civitai_generate` submits the SYNCHRONOUS recipe endpoint (spends
//! Buzz), downloads the signed expiring blob URLs, and lands the files in
//! the office store (`source_tool: "civitai"`) — they render anywhere
//! `kawai-file://` tokens render. Cost display is the docs' pricing formula
//! computed client-side (the API has no free pricing mode — verified live).

use serde::{Deserialize, Serialize};
use std::sync::{LazyLock, Mutex};
use std::time::{Duration, Instant};

use civitai::{Blob, ImageGenParams};

// ── Wire types (camelCase both directions, like logic::topup) ──────────────

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiKeyStatus {
    pub configured: bool,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedImage {
    pub file_id: String,
    pub name: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelCover {
    pub ecosystem: String,
    pub label: String,
    /// The model's card art on civitai (CDN URL) — None when the lookup
    /// found nothing; the UI falls back to the gradient tile.
    pub url: Option<String>,
    pub model_name: Option<String>,
}

/// Top-checkpoint cover art per panel ecosystem (the thing that makes the
/// picker look like civitai's). Public v1 read; cached in-process for 1h —
/// the picker hits this on every panel mount. Cover art rides the LIST
/// payload (`modelVersions[0].images`) — no per-model image calls.
static COVER_CACHE: LazyLock<Mutex<Option<(Instant, Vec<ModelCover>)>>> =
    LazyLock::new(|| Mutex::new(None));
const COVER_TTL: Duration = Duration::from_secs(3600);
/// Panel ecosystem → v1 search query (top Checkpoint by rating).
const COVER_QUERIES: [(&str, &str); 4] = [
    ("anima", "anime"),
    ("sdxl", "sdxl"),
    ("flux1", "flux"),
    ("flux2Klein", "flux klein"),
];

pub async fn civitai_model_covers() -> Result<Vec<ModelCover>, String> {
    if let Some((at, covers)) = COVER_CACHE.lock().ok().and_then(|c| c.clone()) {
        if at.elapsed() < COVER_TTL {
            return Ok(covers);
        }
    }

    let key = kawai_constants::civitai::get_civitai();
    let mut covers = Vec::with_capacity(COVER_QUERIES.len());
    for (ecosystem, query) in COVER_QUERIES {
        let cover = civitai::search_models(&key, query, &["Checkpoint"], 3, Some("Highest Rated"), None)
            .await
            .ok()
            .and_then(|page| {
                page.items.into_iter().find_map(|m| {
                    let url = m
                        .model_versions
                        .as_ref()?
                        .first()?
                        .images
                        .as_ref()?
                        .first()?
                        .url
                        .clone()?;
                    Some(ModelCover {
                        ecosystem: ecosystem.to_string(),
                        label: ecosystem.to_string(),
                        url: Some(url),
                        model_name: Some(m.name),
                    })
                })
            });
        covers.push(cover.unwrap_or(ModelCover {
            ecosystem: ecosystem.to_string(),
            label: ecosystem.to_string(),
            url: None,
            model_name: None,
        }));
    }
    if let Ok(mut c) = COVER_CACHE.lock() {
        *c = Some((Instant::now(), covers.clone()));
    }
    Ok(covers)
}

// ── Resource browser (the civitai model-picker modal) ──────────────────────

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelsArgs {
    /// Target generation ecosystem — the constructed AIR URN carries it.
    pub ecosystem: String,
    #[serde(default)]
    pub query: Option<String>,
    /// `"Checkpoint"` (default) or `"LORA"`.
    #[serde(default)]
    pub model_type: Option<String>,
    /// v1 sort: `"Highest Rated"` (default) | `"Most Downloaded"` | `"Newest"`.
    #[serde(default)]
    pub sort: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
    /// Keyset cursor from the previous page (`nextCursor`) — None = page 1.
    #[serde(default)]
    pub cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelPage {
    pub rows: Vec<SearchModelRow>,
    /// None = no more pages.
    pub next_cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelRow {
    pub model_id: i64,
    pub version_id: i64,
    pub name: String,
    pub creator: Option<String>,
    pub downloads: Option<i64>,
    pub thumbs_up: Option<i64>,
    pub base_model: Option<String>,
    pub cover_url: Option<String>,
    /// HTML description stripped to plain text, capped for the grid card.
    pub description: Option<String>,
    /// Up to 3 showcase images BESIDES the cover — the example strip.
    pub example_urls: Vec<String>,
    /// `urn:air:{ecosystem}:{checkpoint|lora}:civitai:{model}@{version}` —
    /// constructed; list payloads do not carry AIR URNs.
    pub air_urn: String,
}

/// Crude HTML→text (tag stripping + whitespace collapse) — descriptions are
/// display-only snippets, never rendered as HTML.
fn strip_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for ch in s.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            c if !in_tag => out.push(c),
            _ => {}
        }
    }
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn truncate_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let cut: String = s.chars().take(max).collect();
    format!("{cut}…")
}

pub async fn civitai_search_models(args: SearchModelsArgs) -> Result<SearchModelPage, String> {
    let key = require_key()?;
    let is_lora = matches!(args.model_type.as_deref(), Some("LORA") | Some("lora"));
    let model_type = if is_lora { "LORA" } else { "Checkpoint" };
    let limit = args.limit.unwrap_or(20).clamp(1, 50);
    let page = civitai::search_models(
        &key,
        args.query.as_deref().unwrap_or(""),
        &[model_type],
        limit,
        args.sort.as_deref(),
        args.cursor.as_deref(),
    )
    .await?;
    let next_cursor = page.next_cursor();
    let rows = page
        .items
        .into_iter()
        .filter_map(|m| {
            let version = m.model_versions.as_ref()?.first()?;
            let creator = m.creator.and_then(|c| c.username);
            let downloads = m.stats.as_ref().and_then(|s| s.download_count);
            let thumbs_up = m.stats.as_ref().and_then(|s| s.thumbs_up_count);
            // Cover/examples usually ride the FIRST version — but some models
            // only have showcase art on older versions, so scan until found.
            let images = m
                .model_versions
                .as_ref()
                .and_then(|versions| {
                    versions
                        .iter()
                        .find(|v| v.images.as_ref().is_some_and(|imgs| !imgs.is_empty()))
                        .or_else(|| versions.first())
                })
                .and_then(|v| v.images.as_ref())
                .map(|imgs| imgs.iter().filter_map(|i| i.url.clone()).collect::<Vec<_>>())
                .unwrap_or_default();
            let cover_url = images.first().cloned();
            // Example strip: up to 3 showcase images besides the cover.
            let example_urls: Vec<String> = images.into_iter().skip(1).take(3).collect();
            let description = m
                .description
                .as_deref()
                .map(strip_html)
                .filter(|s| !s.is_empty())
                .map(|s| truncate_chars(&s, 220));
            Some(SearchModelRow {
                model_id: m.id,
                version_id: version.id,
                air_urn: format!(
                    "urn:air:{}:{}:civitai:{}@{}",
                    args.ecosystem, kind_segment(is_lora), m.id, version.id
                ),
                name: m.name,
                creator,
                downloads,
                thumbs_up,
                base_model: version.base_model.clone(),
                cover_url,
                description,
                example_urls,
            })
        })
        .collect();
    Ok(SearchModelPage {
        rows,
        next_cursor,
    })
}

fn kind_segment(is_lora: bool) -> &'static str {
    if is_lora {
        "lora"
    } else {
        "checkpoint"
    }
}

// ── API key ────────────────────────────────────────────────────────────────

fn require_key() -> Result<String, String> {
    let key = kawai_constants::civitai::get_civitai();
    if key.trim().is_empty() {
        return Err(
            "Civitai API key belum dikonfigurasi di vault (kawai-vault/constants)".to_string(),
        );
    }
    Ok(key)
}

pub fn civitai_api_key_status() -> ApiKeyStatus {
    ApiKeyStatus {
        configured: !kawai_constants::civitai::get_civitai().trim().is_empty(),
    }
}

// ── Generation ─────────────────────────────────────────────────────────────

fn blob_view(b: &Blob) -> Option<&Blob> {
    b.url
        .as_ref()
        .is_some_and(|u| !u.trim().is_empty())
        .then_some(b)
}

/// Generate images and persist them into the user's office store. The
/// recipe call is synchronous (10–25s at spec defaults; minutes for large
/// batches) and SPENDS Buzz — the panel's Generate click is the consent.
/// Each call creates NEW files (import semantics).
pub async fn civitai_generate(
    user_id: &str,
    params: ImageGenParams,
) -> Result<Vec<SavedImage>, String> {
    let key = require_key()?;
    let result = civitai::submit_image_gen(&key, &params).await?;
    if result.images.is_empty() {
        return Err(result
            .errors
            .and_then(|errs| errs.into_iter().next())
            .unwrap_or_else(|| "Civitai tidak mengembalikan gambar".into()));
    }
    let short_id: String = params.ecosystem.clone() + "-" + &uuidish();
    let mut saved = Vec::with_capacity(result.images.len());
    let mut failed_downloads: Vec<String> = Vec::new();
    for (i, blob) in result.images.iter().filter_map(blob_view).enumerate() {
        let url = blob.url.as_deref().unwrap_or_default();
        let bytes = match civitai::download_bytes(url).await {
            Ok(bytes) => bytes,
            Err(e) => {
                failed_downloads.push(format!("gambar {}: {e}", i + 1));
                continue;
            }
        };
        // Signed URLs end in the real extension (.jpeg/.png); default jpg.
        let ext = if url.split('?').next().is_some_and(|p| p.ends_with(".png")) {
            "png"
        } else {
            "jpg"
        };
        let name = format!("civitai-{short_id}-{}.{}", i + 1, ext);
        let file = kawai_office::store::import_as(
            user_id,
            &name,
            &bytes,
            kawai_office::store::ArtifactKind::Image,
            "civitai",
            None,
        )
        .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
        saved.push(SavedImage {
            file_id: file.id,
            name,
        });
    }
    if saved.is_empty() {
        return Err(format!(
            "semua unduhan gagal: {}",
            failed_downloads.join("; ")
        ));
    }
    if !failed_downloads.is_empty() {
        eprintln!("civitai: {} unduhan gagal", failed_downloads.join("; "));
    }
    Ok(saved)
}

/// Short per-run discriminator for file names (timestamp-based; the office
/// store mints its own opaque ids — this only keeps names readable).
fn uuidish() -> String {
    let d = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    format!("{d:x}")
}
