//! Civitai image + music generation — Generator panel ops (both transports).
//!
//! Pure layer — `reqwest` + the `civitai` client crate + one remote-llm
//! one-shot (music simple-mode drafting), no tauri/axum: BOTH transports
//! (Tauri commands in `commands.rs`, Axum routes in `web.rs`) call these same
//! fns. Identity (`user_id`) is resolved at the transport edge and passed
//! in — the frontend never sends it.
//!
//! Credential model: the Civitai API key is product-baked in
//! `kawai-vault/constants` (`civitai::get_civitai()`, generated by the
//! vault's gen crate). Empty getter = generation unconfigured.
//!
//! Flow: `civitai_generate` submits the recipe endpoint (spends Buzz — the
//! job itself is asynchronous, so the `civitai` client long-polls `?wait=90`
//! and keeps polling the workflow until it turns terminal before returning)
//! then downloads the signed expiring blob URLs and lands the files in the
//! office store (`source_tool: "civitai"`) — they render anywhere
//! `kawai-file://` tokens render. Cost display is the docs' pricing formula
//! computed client-side (the API has no free pricing mode — verified live).

use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{LazyLock, Mutex};
use std::time::{Duration, Instant};

use civitai::{Blob, ImageGenParams};

// ── Token pricing (Buzz → KAWAI token) ─────────────────────────────────────
//
// KAWAI bills usage in app tokens (worker `qris.ts`: `TOKENS_PER_IDR = 100`,
// so 1 token = Rp 0,01). Civitai charges generation in Buzz; its own
// conversion anchor is `BUZZ_PER_USD = 1000` (civitai
// buzz-attribution.service.ts) — 1 Buzz = $0,001. At FX 20.000 IDR/USD that
// is Rp 20 per Buzz = 2.000 tokens; ×1,2 infrastructure margin → 2.400.
// Baked on purpose (repo rule: no env knobs) — keep in sync with the
// frontend twin in `frontend/src/features/generator/ecosystems.ts`.
pub const TOKENS_PER_BUZZ: u64 = 2_400;

/// Convert a Buzz price to app tokens, ALWAYS rounding up — never bill less
/// than the real Buzz spend.
pub fn buzz_to_tokens(buzz: f64) -> u64 {
    (buzz * TOKENS_PER_BUZZ as f64).ceil() as u64
}

/// Image pricing estimate. The image recipes have NO whatif mode (verified
/// live — the parameter is silently ignored), so the price comes from the
/// docs' generation formula (the same one the panel displays):
/// `8 × (W×H/1024²) × (steps/25) × qty`. Upscale passes ride the
/// imageUpscaler recipe (no cost fields either) — each pass doubles the
/// resolution, so a pass is priced at the DOUBLED-dims generation cost
/// (4× the base unit); `txt2img:hires-fix` bills generation + passes,
/// `img2img:upscale` bills passes only. Calibrate against live Buzz spend
/// if civitai reprices.
fn image_buzz_estimate(params: &ImageGenParams) -> f64 {
    let w = params.width as f64;
    let h = params.height as f64;
    let steps = params.steps.unwrap_or(30) as f64;
    let qty = params.quantity.unwrap_or(1) as f64;
    let unit = 8.0 * (w * h / (1024.0 * 1024.0)) * (steps / 25.0) * qty;
    let workflow = params.effective_workflow();
    let generation = if workflow == "img2img:upscale" { 0.0 } else { unit };
    let passes = match workflow {
        "txt2img:hires-fix" | "img2img:upscale" => {
            params.upscale_repeats.unwrap_or(1).max(0) as f64 * 4.0 * unit
        }
        _ => 0.0,
    };
    generation + passes
}

/// Per-process discriminator so two debits inside the same millisecond (the
/// `uuidish()` resolution) never collide on the worker's unique ledger ref.
static DEBIT_SEQ: AtomicU64 = AtomicU64::new(0);

/// Debit the token price off the user's worker balance — FAIL-CLOSED: media
/// spends real Buzz at civitai, so an unreachable worker must block the
/// submit (unlike the LLM turn's fail-open policy). 409
/// `insufficient_balance` arrives as a friendly top-up message.
async fn debit_media_tokens(bearer: &str, tokens: u64) -> Result<(), String> {
    let reference = format!(
        "civitai:{}-{}",
        uuidish(),
        DEBIT_SEQ.fetch_add(1, Ordering::Relaxed)
    );
    match super::topup::billing_debit_ref(bearer, tokens, &reference).await {
        Ok(_) => Ok(()),
        Err(e) if e.contains("insufficient_balance") => Err(format!(
            "Saldo tidak cukup: {tokens} token diperlukan — isi ulang lewat halaman Top Up"
        )),
        Err(e) => Err(format!("debit saldo gagal: {e}")),
    }
}

// ── Wire types (camelCase both directions, like logic::topup) ──────────────

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiKeyStatus {
    pub configured: bool,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedImage {
    pub file_id: String,
    pub name: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelCover {
    pub ecosystem: String,
    pub label: String,
    /// The model's card art on civitai (CDN URL) — None when the lookup
    /// found nothing; the UI falls back to the gradient tile.
    pub url: Option<String>,
    /// Name of the model that will actually run. Set only for the music
    /// lane's pinned records — the image lane's art is a rating-ranked
    /// search hit, never the checkpoint the orchestrator falls back to, so
    /// naming it would claim a provenance the request doesn't carry.
    pub model_name: Option<String>,
}

/// Top-checkpoint cover art per panel ecosystem (the thing that makes the
/// picker look like civitai's). Public v1 read; cached in-process for 1h —
/// the picker hits this on every panel mount. Cover art rides the LIST
/// payload (`modelVersions[0].images`) — no per-model image calls.
static COVER_CACHE: LazyLock<Mutex<Option<(Instant, Vec<ModelCover>)>>> =
    LazyLock::new(|| Mutex::new(None));
const COVER_TTL: Duration = Duration::from_secs(3600);
/// Panel ecosystem → v1 search query (top Checkpoint by rating).
const COVER_QUERIES: [(&str, &str); 4] = [
    ("anima", "anime"),
    ("sdxl", "sdxl"),
    ("flux1", "flux"),
    ("flux2Klein", "flux klein"),
];

/// The music lane's PINNED models — civitai's audio ecosystems are all
/// `modelLocked`, so the card art comes from the version record, not a
/// search. Sonilo's v1 record carries no card ("Missing model file") — its
/// logo URL is baked (civitai's B2 blob store, civitai.com subdomain, so it
/// rides the worker proxy like every other civitai-hosted URL).
const MUSIC_MODEL_VERSIONS: [(&str, i64, &str, Option<&str>); 4] = [
    ("minimax-music3", 3_225_593, "MiniMax Music", None),
    ("yue2", 3_337_846, "YuE2-3B", None),
    (
        "sonilo",
        3_370_181,
        "Sonilo",
        Some("https://blobs-b2.civitai.com/file/blobs-managed-public/F014CSKHPKMVFT6P0VQPEK5AF0.webp"),
    ),
    ("ace", 2_864_949, "ACE-Step Audio Gen", None),
];

pub async fn civitai_model_covers() -> Result<Vec<ModelCover>, String> {
    if let Some((at, covers)) = COVER_CACHE.lock().ok().and_then(|c| c.clone()) {
        if at.elapsed() < COVER_TTL {
            return Ok(covers);
        }
    }

    let key = kawai_constants::civitai::get_civitai();
    let mut covers = Vec::with_capacity(COVER_QUERIES.len() + MUSIC_MODEL_VERSIONS.len());
    for (ecosystem, query) in COVER_QUERIES {
        let cover = civitai::search_models(&key, query, &["Checkpoint"], 3, Some("Highest Rated"), None)
            .await
            .ok()
            .and_then(|page| {
                page.items.into_iter().find_map(|m| {
                    let url = m
                        .model_versions
                        .as_ref()?
                        .first()?
                        .images
                        .as_ref()?
                        .first()?
                        .url
                        .clone()?;
                    Some(ModelCover {
                        ecosystem: ecosystem.to_string(),
                        label: ecosystem.to_string(),
                        url: Some(url),
                        model_name: None,
                    })
                })
            });
        covers.push(cover.unwrap_or(ModelCover {
            ecosystem: ecosystem.to_string(),
            label: ecosystem.to_string(),
            url: None,
            model_name: None,
        }));
    }
    // Music lane: PINNED models — civitai's audio ecosystems are all
    // `modelLocked`, so the card art comes from the version record, not a
    // search. A failed lookup degrades to the static name with no URL.
    for (ecosystem, version_id, fallback_name, direct_cover) in MUSIC_MODEL_VERSIONS {
        let (model_name, url) = match direct_cover {
            // Card art baked outside the v1 API — just proxy it.
            Some(url) => (
                fallback_name.to_string(),
                civitai::rewrite_civitai_url(url).or_else(|| Some(url.to_string())),
            ),
            None => match civitai::model_version_card(&key, version_id).await {
                Ok((name, url)) => {
                    let name = if name.is_empty() { fallback_name } else { &name };
                    (name.to_string(), url)
                }
                Err(_) => (fallback_name.to_string(), None),
            },
        };
        covers.push(ModelCover {
            ecosystem: ecosystem.to_string(),
            label: ecosystem.to_string(),
            url,
            model_name: Some(model_name),
        });
    }
    if let Ok(mut c) = COVER_CACHE.lock() {
        *c = Some((Instant::now(), covers.clone()));
    }
    Ok(covers)
}

// ── Template gallery (empty-state presets) ─────────────────────────────────

/// One community image preset for the image lane's empty state. Clicking it
/// fills the form with the image's generation config AND its resources —
/// the checkpoint (diffuser override) + LoRA stack, each resolved by hash
/// to civitai's canonical AIR URN and family-gated to the selected
/// ecosystem. The gallery is still not a reproduction: the seed is left
/// random and the builtin diffuser renders when no compatible checkpoint
/// resolved.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TemplatePreset {
    /// Worker-proxied CDN URL — the webview renders it directly.
    pub url: String,
    pub width: i64,
    pub height: i64,
    pub prompt: String,
    pub negative_prompt: Option<String>,
    pub steps: Option<i64>,
    pub cfg_scale: Option<f64>,
    /// Civitai sampler display name — meaningful on SD-family ecosystems
    /// only; the frontend applies it conditionally.
    pub sampler: Option<String>,
    /// Checkpoint name from meta, when carried — display caption only.
    pub model_name: Option<String>,
    /// The image's checkpoint as a diffuser override, when its family
    /// matches the selected ecosystem — None otherwise (the builtin
    /// diffuser renders).
    pub checkpoint: Option<TemplateResource>,
    /// The image's LoRA stack (≤4), family-gated the same way.
    pub loras: Vec<TemplateResource>,
}

/// One auto-added model reference: a resolved `meta.resources` hash.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TemplateResource {
    pub name: String,
    /// Civitai's canonical AIR URN, verbatim from the by-hash endpoint.
    pub air_urn: String,
    /// LoRA strength (meta `weight`); checkpoint entries carry none.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strength: Option<f64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TemplateGalleryArgs {
    pub ecosystem: String,
}

/// Panel ecosystem → v1 checkpoint search term (the gallery shows the
/// top-rated checkpoint's showcase for the family; a miss degrades to an
/// empty gallery and the frontend falls back to the plain empty state).
const TEMPLATE_QUERIES: [(&str, &str); 12] = [
    ("anima", "anime"),
    ("sdxl", "sdxl"),
    ("flux1", "flux"),
    ("flux2Klein", "flux klein"),
    ("flux2Dev", "flux dev"),
    ("sd1", "dreamshaper"),
    ("qwen", "qwen image"),
    ("zImageTurbo", "z image"),
    ("zImageBase", "z image"),
    ("wan", "wan"),
    ("seedream", "seedream"),
    ("grok", "grok"),
];

/// Per-ecosystem 1h cache — the empty state hits this on every panel mount
/// and every eco switch, same shape as `COVER_CACHE`.
static TEMPLATE_CACHE: LazyLock<Mutex<std::collections::HashMap<String, (Instant, Vec<TemplatePreset>)>>> =
    LazyLock::new(|| Mutex::new(std::collections::HashMap::new()));
const TEMPLATE_TTL: Duration = Duration::from_secs(3600);

/// Upper bound on copied prompt/negative text — a template fills the form,
/// it must not dump a 10k-char A11-detailer blob into the textarea.
const TEMPLATE_TEXT_CAP: usize = 4000;
/// Per-image LoRA cap (the form's own cap is 9 — templates stay lean).
const TEMPLATE_LORAS_CAP: usize = 4;
/// Hard cap on by-hash calls per gallery refresh — resolution is sequential
/// (no futures dep) and civitai's v1 is rate-limited; a bigger unique-hash
/// set silently skips its leftovers until the next cache expiry.
const TEMPLATE_RESOLVE_BUDGET: usize = 12;

fn cap_text(value: Option<String>) -> Option<String> {
    let trimmed = value?.trim().to_string();
    if trimmed.is_empty() {
        return None;
    }
    Some(truncate_chars(&trimmed, TEMPLATE_TEXT_CAP))
}

/// A by-hash resolution kept across refreshes — hashes repeat heavily
/// (community images cluster on the same checkpoint/LoRAs), so the cache is
/// the thing that keeps the sequential calls bounded in practice.
type ResolvedResource = Option<(String, String, Option<String>)>;
static RESOURCE_CACHE: LazyLock<
    Mutex<std::collections::HashMap<String, (Instant, ResolvedResource)>>,
> = LazyLock::new(|| Mutex::new(std::collections::HashMap::new()));
const RESOURCE_TTL: Duration = Duration::from_secs(24 * 3600);

/// `(air_urn, name, base_model)` for one resources hash — `None` when
/// civitai carries no version for it. Display name comes from the meta
/// resources entry (the by-hash response carries none).
async fn resolve_resource(
    key: &str,
    hash: &str,
    name: &str,
    budget: &mut usize,
) -> Result<ResolvedResource, String> {
    if let Some((at, resolved)) = RESOURCE_CACHE.lock().ok().and_then(|m| m.get(hash).cloned()) {
        if at.elapsed() < RESOURCE_TTL {
            return Ok(resolved);
        }
    }
    if *budget == 0 {
        // Cache miss but the refresh's call budget is spent — report
        // "unknown" WITHOUT caching, so a later refresh resolves it.
        return Ok(None);
    }
    *budget -= 1;
    let resolved = civitai::model_version_by_hash(key, hash)
        .await?
        .map(|v| (v.air.unwrap_or_default(), name.to_string(), v.base_model))
        .filter(|(air, _, _)| !air.is_empty());
    if let Ok(mut cache) = RESOURCE_CACHE.lock() {
        cache.insert(hash.to_string(), (Instant::now(), resolved.clone()));
    }
    Ok(resolved)
}

pub async fn civitai_template_gallery(args: TemplateGalleryArgs) -> Result<Vec<TemplatePreset>, String> {
    let ecosystem = args.ecosystem.trim().to_string();
    if ecosystem.is_empty() {
        return Ok(Vec::new());
    }
    if let Some((at, presets)) = TEMPLATE_CACHE
        .lock()
        .ok()
        .and_then(|m| m.get(&ecosystem).cloned())
    {
        if at.elapsed() < TEMPLATE_TTL {
            return Ok(presets);
        }
    }

    let key = require_key()?;
    let query = TEMPLATE_QUERIES
        .iter()
        .find(|(id, _)| *id == ecosystem)
        .map(|(_, q)| *q)
        .unwrap_or(ecosystem.as_str());

    // Top-rated checkpoint for the family → its first version's showcase
    // feed, reactions-ranked, meta-carrying images only (authors who
    // stripped their generation data are useless as templates).
    let version_id = civitai::search_models(&key, query, &["Checkpoint"], 3, Some("Highest Rated"), None)
        .await
        .ok()
        .and_then(|page| page.items.into_iter().find_map(|m| m.model_versions.and_then(|v| v.first().map(|first| first.id))));
    let Some(version_id) = version_id else {
        if let Ok(mut cache) = TEMPLATE_CACHE.lock() {
            cache.insert(ecosystem, (Instant::now(), Vec::new()));
        }
        return Ok(Vec::new());
    };

    let hits = civitai::search_images(&key, version_id, 40, "Most Reactions", "AllTime").await?;
    // Family gate for auto-attached checkpoint/LoRAs: the AIR may only ride
    // the request when its base-model family equals the ecosystem's own —
    // a cross-family diffuser override would 400 at the orchestrator. The
    // unclassified ecosystems (anima, flux2/zImage, the engines) have no
    // confident mapping, so nothing auto-attaches there — their builtin
    // diffuser is the point of picking them anyway.
    let eco_family = civitai::registry::ecosystem_family(&ecosystem);
    let family_of = |base: &Option<String>| -> Option<&'static str> {
        eco_family.and_then(|eco| base.as_deref().and_then(civitai::registry::base_model_family).and_then(|f| (f == eco).then_some(f)))
    };
    let mut resolve_budget = TEMPLATE_RESOLVE_BUDGET;
    let mut raw: Vec<(civitai::V1ImageHit, civitai::V1ImageMeta)> = Vec::new();
    for hit in hits {
        // SFW double-guard: `nsfw=None` on the wire plus this client-side
        // level filter (the flag maps to a browsing level, not the enum).
        if hit.nsfw_level.as_deref().unwrap_or("None") != "None" {
            continue;
        }
        let Some(meta) = hit.meta.clone() else { continue };
        if raw.len() < 12 {
            raw.push((hit, meta));
        } else {
            break;
        }
    }

    let mut presets: Vec<TemplatePreset> = Vec::with_capacity(raw.len());
    for (hit, meta) in raw {
        let Some(prompt) = cap_text(meta.prompt.clone()) else { continue };
        let Some(url) = hit.url.clone().filter(|u| !u.is_empty()) else { continue };

        // Resources: resolve hashes → AIR, gate each by family.
        let mut checkpoint: Option<TemplateResource> = None;
        let mut loras: Vec<TemplateResource> = Vec::new();
        for entry in meta.resources.iter().flatten() {
            let Some(hash) = entry.hash.as_deref().filter(|h| !h.trim().is_empty()) else { continue };
            let kind = entry.kind.as_deref().unwrap_or("");
            if kind != "model" && kind != "lora" {
                continue; // VAE / embeddings / TI — nothing the form carries
            }
            if kind == "lora" && loras.len() >= TEMPLATE_LORAS_CAP {
                continue;
            }
            if checkpoint.is_some() && kind != "lora" {
                continue; // one checkpoint per template
            }
            let name = entry
                .name
                .clone()
                .filter(|n| !n.trim().is_empty())
                .unwrap_or_else(|| hash.to_string());
            let Ok(Some((air, name, base))) = resolve_resource(&key, hash, &name, &mut resolve_budget).await
            else {
                continue;
            };
            if family_of(&base).is_none() {
                continue;
            }
            let resource = TemplateResource {
                name,
                air_urn: air,
                strength: if kind == "lora" {
                    Some(entry.weight.unwrap_or(1.0).clamp(0.0, 4.0))
                } else {
                    None
                },
            };
            if kind == "lora" {
                loras.push(resource);
            } else {
                checkpoint = Some(resource);
            }
        }

        presets.push(TemplatePreset {
            url,
            width: hit.width.unwrap_or(1024).max(64),
            height: hit.height.unwrap_or(1024).max(64),
            prompt,
            negative_prompt: cap_text(meta.negative_prompt),
            steps: meta.steps,
            cfg_scale: meta.cfg_scale,
            sampler: meta.sampler,
            model_name: meta.model,
            checkpoint,
            loras,
        });
    }

    if let Ok(mut cache) = TEMPLATE_CACHE.lock() {
        cache.insert(ecosystem.clone(), (Instant::now(), presets.clone()));
    }
    Ok(presets)
}

// ── Resource browser (the civitai model-picker modal) ──────────────────────

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelsArgs {
    /// Target generation ecosystem — the constructed AIR URN carries it,
    /// and rows whose v1 `baseModel` maps to a DIFFERENT known family are
    /// dropped (both sides unclassified = kept, the orchestrator decides).
    pub ecosystem: String,
    #[serde(default)]
    pub query: Option<String>,
    /// `"Checkpoint"` (default) or `"LORA"`.
    #[serde(default)]
    pub model_type: Option<String>,
    /// v1 sort: `"Highest Rated"` (default) | `"Most Downloaded"` | `"Newest"`.
    #[serde(default)]
    pub sort: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
    /// Keyset cursor from the previous page (`nextCursor`) — None = page 1.
    #[serde(default)]
    pub cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelPage {
    pub rows: Vec<SearchModelRow>,
    /// None = no more pages.
    pub next_cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelRow {
    pub model_id: i64,
    pub version_id: i64,
    pub name: String,
    pub creator: Option<String>,
    pub downloads: Option<i64>,
    pub thumbs_up: Option<i64>,
    pub base_model: Option<String>,
    pub cover_url: Option<String>,
    /// HTML description stripped to plain text, capped for the grid card.
    pub description: Option<String>,
    /// Up to 3 showcase images BESIDES the cover — the example strip.
    pub example_urls: Vec<String>,
    /// `urn:air:{ecosystem}:{checkpoint|lora}:civitai:{model}@{version}` —
    /// constructed; list payloads do not carry AIR URNs.
    pub air_urn: String,
}

/// Crude HTML→text (tag stripping + whitespace collapse) — descriptions are
/// display-only snippets, never rendered as HTML.
fn strip_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for ch in s.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            c if !in_tag => out.push(c),
            _ => {}
        }
    }
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn truncate_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let cut: String = s.chars().take(max).collect();
    format!("{cut}…")
}

pub async fn civitai_search_models(args: SearchModelsArgs) -> Result<SearchModelPage, String> {
    let key = require_key()?;
    let is_lora = matches!(args.model_type.as_deref(), Some("LORA") | Some("lora"));
    let model_type = if is_lora { "LORA" } else { "Checkpoint" };
    let limit = args.limit.unwrap_or(20).clamp(1, 50);
    let page = civitai::search_models(
        &key,
        args.query.as_deref().unwrap_or(""),
        &[model_type],
        limit,
        args.sort.as_deref(),
        args.cursor.as_deref(),
    )
    .await?;
    let next_cursor = page.next_cursor();
    let eco_family = civitai::registry::ecosystem_family(&args.ecosystem);
    let rows = page
        .items
        .into_iter()
        .filter_map(|m| {
            let version = m.model_versions.as_ref()?.first()?;
            let creator = m.creator.and_then(|c| c.username);
            let downloads = m.stats.as_ref().and_then(|s| s.download_count);
            let thumbs_up = m.stats.as_ref().and_then(|s| s.thumbs_up_count);
            // Cover/examples usually ride the FIRST version — but some models
            // only have showcase art on older versions, so scan until found.
            let images = m
                .model_versions
                .as_ref()
                .and_then(|versions| {
                    versions
                        .iter()
                        .find(|v| v.images.as_ref().is_some_and(|imgs| !imgs.is_empty()))
                        .or_else(|| versions.first())
                })
                .and_then(|v| v.images.as_ref())
                .map(|imgs| imgs.iter().filter_map(|i| i.url.clone()).collect::<Vec<_>>())
                .unwrap_or_default();
            let cover_url = images.first().cloned();
            // Example strip: up to 3 showcase images besides the cover.
            let example_urls: Vec<String> = images.into_iter().skip(1).take(3).collect();
            let description = m
                .description
                .as_deref()
                .map(strip_html)
                .filter(|s| !s.is_empty())
                .map(|s| truncate_chars(&s, 220));
            Some(SearchModelRow {
                model_id: m.id,
                version_id: version.id,
                air_urn: format!(
                    "urn:air:{}:{}:civitai:{}@{}",
                    args.ecosystem, kind_segment(is_lora), m.id, version.id
                ),
                name: m.name,
                creator,
                downloads,
                thumbs_up,
                base_model: version.base_model.clone(),
                cover_url,
                description,
                example_urls,
            })
        })
        // Model follows ecosystem: drop rows whose base model maps to a
        // different KNOWN family (either side unclassified = kept — the
        // orchestrator, not a prefix table, has the last word).
        .filter(|row| match (
            eco_family,
            row.base_model
                .as_deref()
                .and_then(civitai::registry::base_model_family),
        ) {
            (Some(a), Some(b)) => a == b,
            _ => true,
        })
        .collect();
    Ok(SearchModelPage {
        rows,
        next_cursor,
    })
}

fn kind_segment(is_lora: bool) -> &'static str {
    if is_lora {
        "lora"
    } else {
        "checkpoint"
    }
}

// ── API key ────────────────────────────────────────────────────────────────

fn require_key() -> Result<String, String> {
    let key = kawai_constants::civitai::get_civitai();
    if key.trim().is_empty() {
        return Err(
            "Civitai API key belum dikonfigurasi di vault (kawai-vault/constants)".to_string(),
        );
    }
    Ok(key)
}

pub fn civitai_api_key_status() -> ApiKeyStatus {
    ApiKeyStatus {
        configured: !kawai_constants::civitai::get_civitai().trim().is_empty(),
    }
}

// ── Generation ─────────────────────────────────────────────────────────────

fn blob_view(b: &Blob) -> Option<&Blob> {
    b.url
        .as_ref()
        .is_some_and(|u| !u.trim().is_empty())
        .then_some(b)
}

/// Generate images and persist them into the user's office store. The
/// recipe call SPENDS Buzz — the panel's Generate click is the consent —
/// and blocks until the job is terminal: the `civitai` client long-polls
/// `?wait=90`, then polls the workflow until it turns terminal (spec
/// defaults finish in 10–25s; large batches run minutes, hence the 180s
/// poll deadline). Each call creates NEW files (import semantics).
/// Submit the image-gen recipe. SPENDS Buzz — the panel's Generate click is
/// the consent. Billing: the docs' formula estimate is debited off the
/// user's token balance BEFORE the submit (fail-closed — no balance, no
/// generation), with the Civitai Buzz charge mirroring it at the baked
/// account.
pub async fn civitai_generate(
    user_id: &str,
    bearer: &str,
    params: ImageGenParams,
) -> Result<Vec<SavedImage>, String> {
    // Validate BEFORE any money moves — a rejected shape must never cost the
    // user a debit (the submit path re-validates; this is the gate).
    params.validate()?;
    debit_media_tokens(bearer, buzz_to_tokens(image_buzz_estimate(&params))).await?;
    let key = require_key()?;
    let result = civitai::submit_image_gen(&key, &params).await?;
    if result.images.is_empty() {
        return Err(result
            .errors
            .and_then(|errs| errs.into_iter().next())
            .unwrap_or_else(|| "Civitai tidak mengembalikan gambar".into()));
    }
    let short_id: String = params.ecosystem.clone() + "-" + &uuidish();
    let mut saved = Vec::with_capacity(result.images.len());
    let mut failed_downloads: Vec<String> = Vec::new();
    for (i, blob) in result.images.iter().filter_map(blob_view).enumerate() {
        let url = blob.url.as_deref().unwrap_or_default();
        let bytes = match civitai::download_bytes(url).await {
            Ok(bytes) => bytes,
            Err(e) => {
                failed_downloads.push(format!("gambar {}: {e}", i + 1));
                continue;
            }
        };
        // Signed URLs end in the real extension (.jpeg/.png); default jpg.
        let ext = if url.split('?').next().is_some_and(|p| p.ends_with(".png")) {
            "png"
        } else {
            "jpg"
        };
        let name = format!("civitai-{short_id}-{}.{}", i + 1, ext);
        let file = kawai_office::store::import_as(
            user_id,
            &name,
            &bytes,
            kawai_office::store::ArtifactKind::Image,
            "civitai",
            None,
        )
        .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
        saved.push(SavedImage {
            file_id: file.id,
            name,
        });
    }
    if saved.is_empty() {
        return Err(format!(
            "semua unduhan gagal: {}",
            failed_downloads.join("; ")
        ));
    }
    if !failed_downloads.is_empty() {
        eprintln!("civitai: {} unduhan gagal", failed_downloads.join("; "));
    }
    Ok(saved)
}

/// Short per-run discriminator for file names (timestamp-based; the office
/// store mints its own opaque ids — this only keeps names readable).
fn uuidish() -> String {
    let d = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    format!("{d:x}")
}

// ── Video generation (workflows API) ───────────────────────────────────────
//
// Video runs through the workflow surface, not a recipe: the image path
// hides its own polling behind the recipe call, while video hands the
// workflowId back to the panel. submit spends Buzz and returns a
// workflowId; the panel polls
// `civitai_video_status` (server-side long-poll) until a terminal state,
// then `civitai_video_fetch` downloads the signed mp4 ONCE into the office
// store. Restart-safe by design — the workflowId lives client-side, and
// status/fetch are idempotent reads; nothing generation-shaped lives in
// memory between calls.

/// Panel request shape — camelCase from both transports, mapped onto the
/// client's `VideoGenParams`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoGenRequest {
    pub ecosystem: String,
    #[serde(default)]
    pub workflow: Option<String>,
    #[serde(default)]
    pub prompt: Option<String>,
    #[serde(default)]
    pub negative_prompt: Option<String>,
    /// Source frames, ordered: img2vid = [first, (last)]; ref2vid = refs.
    #[serde(default)]
    pub images: Vec<String>,
    /// Source video for `vid2vid:edit` (grok v1.0) — data URL / base64 / URL.
    #[serde(default)]
    pub video: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub fast_mode: Option<bool>,
    #[serde(default)]
    pub duration: Option<i64>,
    #[serde(default)]
    pub resolution: Option<String>,
    #[serde(default)]
    pub aspect_ratio: Option<String>,
    #[serde(default)]
    pub generate_audio: Option<bool>,
    #[serde(default)]
    pub enable_prompt_enhancer: Option<bool>,
    #[serde(default)]
    pub cfg_scale: Option<f64>,
    #[serde(default)]
    pub steps: Option<i64>,
    #[serde(default)]
    pub draft: Option<bool>,
    #[serde(default)]
    pub style: Option<String>,
    #[serde(default)]
    pub movement_amplitude: Option<String>,
    #[serde(default)]
    pub seed: Option<i64>,
    #[serde(default)]
    pub quantity: Option<i64>,
}

impl VideoGenRequest {
    fn to_params(&self) -> civitai::VideoGenParams {
        civitai::VideoGenParams {
            ecosystem: self.ecosystem.clone(),
            workflow: self.workflow.clone(),
            prompt: self.prompt.clone().unwrap_or_default(),
            negative_prompt: self.negative_prompt.clone(),
            images: self.images.clone(),
            video: self.video.clone(),
            model: self.model.clone(),
            mode: self.mode.clone(),
            fast_mode: self.fast_mode,
            duration: self.duration,
            resolution: self.resolution.clone(),
            aspect_ratio: self.aspect_ratio.clone(),
            generate_audio: self.generate_audio,
            enable_prompt_enhancer: self.enable_prompt_enhancer,
            cfg_scale: self.cfg_scale,
            steps: self.steps,
            draft: self.draft,
            style: self.style.clone(),
            movement_amplitude: self.movement_amplitude.clone(),
            seed: self.seed,
            quantity: self.quantity,
        }
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoCostView {
    pub total_buzz: f64,
    /// App-token twin of `total_buzz` (ceil) — what the balance will be
    /// debited at submit. Displayed as the panel's ≈ pill.
    pub total_tokens: u64,
    pub ready: bool,
    pub warnings: Vec<String>,
}

/// Free cost estimate (whatif — no persist, no charge). A failure here means
/// submit would fail too: surface it as the error.
pub async fn civitai_video_cost(req: VideoGenRequest) -> Result<VideoCostView, String> {
    let key = require_key()?;
    let est = civitai::whatif_video_gen(&key, &req.to_params()).await?;
    Ok(VideoCostView {
        total_buzz: est.total_buzz,
        total_tokens: buzz_to_tokens(est.total_buzz),
        ready: est.ready,
        warnings: est.warnings,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoSubmitView {
    pub workflow_id: String,
}

/// Submit the videoGen workflow. SPENDS Buzz — the panel's Generate click
/// (with the whatif cost displayed) is the consent. The token debit rides
/// the same whatif price and happens BEFORE the submit — fail-closed: media
/// spends real Buzz, so an unreachable/depleted balance must block here,
/// never after the Buzz is gone. Returns the workflowId the panel stores
/// and polls.
pub async fn civitai_video_submit(
    _user_id: &str,
    bearer: &str,
    req: VideoGenRequest,
) -> Result<VideoSubmitView, String> {
    let key = require_key()?;
    let params = req.to_params();
    let est = civitai::whatif_video_gen(&key, &params).await?;
    debit_media_tokens(bearer, buzz_to_tokens(est.total_buzz)).await?;
    let submitted = civitai::submit_video_gen(&key, &params).await?;
    Ok(VideoSubmitView {
        workflow_id: submitted.id,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoBlobView {
    pub video_url: String,
    pub thumbnail_url: Option<String>,
    pub width: Option<i64>,
    pub height: Option<i64>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoStatusView {
    pub workflow_id: String,
    /// Normalized: `queued` | `processing` | `succeeded` | `failed` |
    /// `expired` | `canceled` (anything else passes through lowercased).
    pub status: String,
    pub queue_position: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video: Option<VideoBlobView>,
    /// LTX-style batched jobs: extra clips beyond the primary video.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub additional: Vec<VideoBlobView>,
    pub error: Option<String>,
}

/// Poll one workflow (server-side long-poll — the call holds up to
/// `wait_secs`, default 15, before replying with the current snapshot).
pub async fn civitai_video_status(
    workflow_id: String,
    wait_secs: Option<u64>,
) -> Result<VideoStatusView, String> {
    if workflow_id.trim().is_empty() {
        return Err("workflowId kosong".into());
    }
    let key = require_key()?;
    let wf = civitai::video_workflow_status(&key, workflow_id.trim(), wait_secs.unwrap_or(15))
        .await?;
    let status = match wf.status.as_str() {
        "unassigned" | "preparing" | "scheduled" => "queued".to_string(),
        other => other.to_string(),
    };
    Ok(VideoStatusView {
        workflow_id: wf.id,
        queue_position: wf.queue_position,
        video: wf.video_url.map(|video_url| VideoBlobView {
            video_url,
            thumbnail_url: wf.thumbnail_url,
            width: wf.width,
            height: wf.height,
        }),
        additional: wf
            .additional
            .into_iter()
            .map(|m| VideoBlobView {
                video_url: m.url,
                thumbnail_url: m.thumbnail_url,
                width: m.width,
                height: m.height,
            })
            .collect(),
        error: wf.error,
        status,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedVideo {
    pub file_id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail_file_id: Option<String>,
    /// LTX-style batched jobs: the extra clips, imported after the primary.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub additional: Vec<SavedVideo>,
}

/// Cancel a queued/running workflow (`PUT` `{status:"canceled"}` — civitai's
/// own client shape). Best-effort from the panel: the job card's cancel
/// button calls this, then stops polling; the workflow settles `canceled`.
pub async fn civitai_video_cancel(workflow_id: String) -> Result<(), String> {
    let workflow_id = workflow_id.trim().to_string();
    if workflow_id.is_empty() {
        return Err("workflowId kosong".into());
    }
    let key = require_key()?;
    civitai::cancel_video_workflow(&key, &workflow_id).await
}

/// Download the finished video (SIGNED, EXPIRING URL — fetch once) into the
/// office store as `ArtifactKind::Video`, plus its poster thumbnail as an
/// image. Idempotence is the CALLER's job: poll status, and call fetch
/// exactly once per workflow (re-fetching would duplicate files — import
/// semantics always create new entries).
pub async fn civitai_video_fetch(
    user_id: &str,
    workflow_id: String,
    video_url: String,
    thumbnail_url: Option<String>,
    additional_urls: Vec<String>,
) -> Result<SavedVideo, String> {
    let _ = require_key()?; // same baked identity; the URL itself carries the signature
    let workflow_id = workflow_id.trim().to_string();
    if workflow_id.is_empty() || video_url.trim().is_empty() {
        return Err("workflowId dan videoUrl wajib diisi".into());
    }
    let bytes = civitai::download_bytes(video_url.trim())
        .await
        .map_err(|e| format!("unduh video gagal: {e}"))?;
    // Signed URLs end in the real extension; videos are mp4 almost always,
    // webm occasionally.
    let ext = match video_url.split('?').next().and_then(|p| {
        p.rsplit('.')
            .next()
            .map(|e| e.to_ascii_lowercase())
    }) {
        Some(e) if e == "webm" || e == "mov" || e == "m4v" => e,
        _ => "mp4".to_string(),
    };
    let idish: String = workflow_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(12)
        .collect();
    let name = format!("civitai-video-{idish}-{}.{}", uuidish(), ext);
    let file = kawai_office::store::import_as(
        user_id,
        &name,
        &bytes,
        kawai_office::store::ArtifactKind::Video,
        "civitai",
        None,
    )
    .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
    let mut thumbnail_file_id = None;
    if let Some(thumb) = thumbnail_url.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
        match civitai::download_bytes(thumb).await {
            Ok(bytes) => {
                let tname = format!("civitai-video-{idish}-thumb.jpg");
                if let Ok(file) = kawai_office::store::import_as(
                    user_id,
                    &tname,
                    &bytes,
                    kawai_office::store::ArtifactKind::Image,
                    "civitai",
                    None,
                ) {
                    thumbnail_file_id = Some(file.id);
                }
            }
            // Poster is best-effort — the <video> element renders its own
            // first frame when the thumbnail is missing.
            Err(e) => eprintln!("civitai: thumbnail unduh gagal: {e}"),
        }
    }
    // Batched jobs (LTX): import the extra clips after the primary. A failed
    // extra clip is logged, not fatal — the primary result still lands.
    let mut additional = Vec::new();
    for (i, url) in additional_urls.iter().enumerate() {
        if url.trim().is_empty() {
            continue;
        }
        match import_video_file(user_id, &workflow_id, url, i + 2).await {
            Ok(saved) => additional.push(saved),
            Err(e) => eprintln!("civitai: klip tambahan {} gagal: {e}", i + 2),
        }
    }
    Ok(SavedVideo {
        file_id: file.id,
        name,
        thumbnail_file_id,
        additional,
    })
}

/// Download one video URL into the store (shared by primary + batch clips).
async fn import_video_file(
    user_id: &str,
    workflow_id: &str,
    video_url: &str,
    ordinal: usize,
) -> Result<SavedVideo, String> {
    let bytes = civitai::download_bytes(video_url.trim())
        .await
        .map_err(|e| format!("unduh video gagal: {e}"))?;
    let ext = match video_url.split('?').next().and_then(|p| {
        p.rsplit('.')
            .next()
            .map(|e| e.to_ascii_lowercase())
    }) {
        Some(e) if e == "webm" || e == "mov" || e == "m4v" => e,
        _ => "mp4".to_string(),
    };
    let idish: String = workflow_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(12)
        .collect();
    // `civitai-video-<id>-<n>.<ext>` — the ext decides the ArtifactKind,
    // the uuid suffix only uniquifies the stem.
    let name = format!(
        "civitai-video-{idish}-{ordinal}.{}.{}",
        uuidish(),
        ext
    );
    let file = kawai_office::store::import_as(
        user_id,
        &name,
        &bytes,
        kawai_office::store::ArtifactKind::Video,
        "civitai",
        None,
    )
    .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
    Ok(SavedVideo {
        file_id: file.id,
        name,
        thumbnail_file_id: None,
        additional: Vec::new(),
    })
}

// ── Civitai MUSIC generation (txt2music — workflows API) ───────────────────
//
// Same op shapes as the video lane. Simple mode drafts the structured fields
// (caption/lyrics, or lyrics/musicDescription/bpm/key on ACE) through the
// remote-llm pool — mirroring civitai's own chatCompletion drafting step
// (`music-concept.ts`, prompts quoted verbatim) — then submits custom-mode
// steps, so the orchestrator runs one step fewer.

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MusicGenRequest {
    pub ecosystem: String,
    /// "simple" (one prompt, drafted here) | "custom" (direct fields).
    #[serde(default)]
    pub mode: Option<String>,
    /// Sonilo only: "music" (default) | "soundEffect".
    #[serde(default)]
    pub operation: Option<String>,
    /// Simple-mode prompt (the drafting input).
    #[serde(default)]
    pub prompt: Option<String>,
    /// MiniMax/ACE music description; Sonilo prompt (custom mode).
    #[serde(default)]
    pub caption: Option<String>,
    #[serde(default)]
    pub lyrics: Option<String>,
    /// YuE2: ABC score.
    #[serde(default)]
    pub abc: Option<String>,
    /// YuE2: "full" (default) | "melody" | "off".
    #[serde(default)]
    pub score_mode: Option<String>,
    #[serde(default)]
    pub steps: Option<i64>,
    /// ACE: 40–200.
    #[serde(default)]
    pub bpm: Option<i64>,
    /// ACE: musical key.
    #[serde(default)]
    pub key: Option<String>,
    #[serde(default)]
    pub instrumental_weight: Option<f64>,
    #[serde(default)]
    pub vocal_weight: Option<f64>,
    #[serde(default)]
    pub cfg_scale: Option<f64>,
    /// ACE variant: "xl-turbo" (default) | "turbo" | "xl-sft" | "xl-base" | "base".
    #[serde(default)]
    pub model: Option<String>,
    /// ACE cover image (URL / data URL / base64).
    #[serde(default)]
    pub cover_image: Option<String>,
    /// Seconds (Sonilo soundEffect takes 0.5 steps).
    #[serde(default)]
    pub duration: Option<f64>,
    #[serde(default)]
    pub seed: Option<i64>,
}

impl MusicGenRequest {
    fn is_simple(&self) -> bool {
        self.mode.as_deref() == Some("simple")
    }

    fn to_params(&self) -> civitai::MusicGenParams {
        civitai::MusicGenParams {
            ecosystem: self.ecosystem.clone(),
            mode: self.mode.clone(),
            operation: self.operation.clone(),
            caption: self.caption.clone(),
            lyrics: self.lyrics.clone(),
            abc: self.abc.clone(),
            score_mode: self.score_mode.clone(),
            steps: self.steps,
            bpm: self.bpm,
            key: self.key.clone(),
            instrumental_weight: self.instrumental_weight,
            vocal_weight: self.vocal_weight,
            cfg_scale: self.cfg_scale,
            model: self.model.clone(),
            cover_image: self.cover_image.clone(),
            duration: self.duration,
            seed: self.seed,
        }
    }
}

/// civitai's simple-mode drafting contract for models that take caption +
/// lyrics (`music-concept.ts` — MiniMax reads the caption as three labelled
/// sections; the shape is prescribed, not left to the model).
const MUSIC_CONCEPT_SYSTEM: &str = "You write song concepts for a music generation model. The caption must be a structured description with three labelled sections — Global Metadata (genre, subgenre, BPM, key, scale, emotional progression, production profile), Vocal Details (vocal gender, timbre, performance style, harmony, effects) and Arrangement (primary and secondary instruments, section-level evolution, groove, bass, percussion, textures). The lyrics must use section markers such as [Intro], [Verse], [Pre-Chorus], [Chorus], [Bridge] and [Outro]. Respond with JSON {\"caption\": string, \"lyrics\": string}.";

/// ACE's shorter simple-mode drafting contract (its own system prompt +
/// JSON shape — lyrics/description/bpm/key).
const ACE_CONCEPT_SYSTEM: &str = "You write short song concepts. Respond with JSON {\"lyrics\": string, \"musicDescription\": string, \"bpm\": integer (40-200), \"key\": string}.";

/// Resolve simple mode → final content fields: one cloud one-shot drafts
/// caption/lyrics (MiniMax/YuE2) or lyrics/musicDescription/bpm/key (ACE)
/// from the user's prompt, mirroring civitai's own chatCompletion drafting
/// step. Duration shapes the drafting ask, matching civitai's user message.
async fn finalize_request(req: &MusicGenRequest) -> Result<civitai::MusicGenParams, String> {
    let ecosystem = civitai::registry::music_ecosystem(&req.ecosystem)
        .ok_or_else(|| format!("ecosystem music '{}' tidak dikenal", req.ecosystem))?
        .key;
    let duration = req.duration.unwrap_or_else(|| {
        let eco = civitai::registry::music_ecosystem(&req.ecosystem).expect("checked above");
        let op = match req.operation.as_deref() {
            Some("soundEffect") => "soundEffect",
            _ => "music",
        };
        registry_duration_default(eco, op)
    });

    let mut final_req = MusicGenRequest {
        ecosystem: req.ecosystem.clone(),
        mode: Some("custom".into()),
        operation: req.operation.clone(),
        prompt: req.prompt.clone(),
        caption: req.caption.clone(),
        lyrics: req.lyrics.clone(),
        abc: req.abc.clone(),
        score_mode: req.score_mode.clone(),
        steps: req.steps,
        bpm: req.bpm,
        key: req.key.clone(),
        instrumental_weight: req.instrumental_weight,
        vocal_weight: req.vocal_weight,
        cfg_scale: req.cfg_scale,
        model: req.model.clone(),
        cover_image: req.cover_image.clone(),
        duration: req.duration,
        seed: req.seed,
    };

    if req.is_simple() && ecosystem != "sonilo" {
        let prompt = req
            .prompt
            .as_deref()
            .map(str::trim)
            .filter(|p| !p.is_empty())
            .ok_or_else(|| "prompt wajib diisi untuk mode simple".to_string())?;
        let (system, task, role) = if ecosystem == "ace" {
            (
                ACE_CONCEPT_SYSTEM,
                format!(
                    "Write a {duration}-second song. {prompt}. Output JSON with lyrics, musicDescription, bpm (40-200), key."
                ),
                "music-concept-ace",
            )
        } else {
            (
                MUSIC_CONCEPT_SYSTEM,
                format!(
                    "Write a song of at most {duration} seconds. {prompt}. Output JSON with caption and lyrics."
                ),
                "music-concept",
            )
        };
        let answer = remote_llm::reason::reason_in(system, &task, role, None, None)
            .await
            .map_err(|e| format!("gagal menyusun konsep lagu: {e}"))?;
        let parsed: serde_json::Value = serde_json::from_str(&remote_llm::reason::extract_json(
            &answer,
        ))
        .map_err(|e| format!("konsep lagu dari model tidak valid: {e}"))?;
        if ecosystem == "ace" {
            final_req.caption = Some(
                parsed
                    .get("musicDescription")
                    .and_then(|v| v.as_str())
                    .unwrap_or_default()
                    .to_string(),
            );
            final_req.lyrics = Some(
                parsed
                    .get("lyrics")
                    .and_then(|v| v.as_str())
                    .unwrap_or_default()
                    .to_string(),
            );
            final_req.bpm = parsed.get("bpm").and_then(|v| v.as_i64());
            final_req.key = parsed
                .get("key")
                .and_then(|v| v.as_str())
                .map(str::to_string);
        } else {
            final_req.caption = Some(
                parsed
                    .get("caption")
                    .and_then(|v| v.as_str())
                    .unwrap_or_default()
                    .to_string(),
            );
            final_req.lyrics = Some(
                parsed
                    .get("lyrics")
                    .and_then(|v| v.as_str())
                    .unwrap_or_default()
                    .to_string(),
            );
        }
    }

    // Sonilo takes ONE prompt and the panel sends it as `prompt` — the crate
    // carries it in `caption` (its single content field).
    if ecosystem == "sonilo" {
        let prompt = final_req
            .prompt
            .take()
            .or(final_req.caption.take())
            .unwrap_or_default();
        final_req.caption = Some(prompt);
    }

    Ok(final_req.to_params())
}

/// Sonilo's soundEffect default differs from the ecosystem default.
fn registry_duration_default(
    eco: &civitai::registry::MusicEcosystem,
    operation: &str,
) -> f64 {
    let (_, _, default, _) = civitai::registry::music_duration_bounds(eco, operation);
    default
}

/// Free cost estimate (whatif). Simple mode drafts first — the price of the
/// music step does not depend on the drafted text, so this matches what
/// submit will spend.
pub async fn civitai_music_cost(req: MusicGenRequest) -> Result<VideoCostView, String> {
    let key = require_key()?;
    let params = finalize_request(&req).await?;
    let est = civitai::whatif_music_gen(&key, &params).await?;
    Ok(VideoCostView {
        total_buzz: est.total_buzz,
        total_tokens: buzz_to_tokens(est.total_buzz),
        ready: est.ready,
        warnings: est.warnings,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MusicSubmitView {
    pub workflow_id: String,
}

/// Submit the music workflow. SPENDS Buzz — the panel's Generate click
/// (with the whatif cost displayed) is the consent. The token debit happens
/// after the whatif pre-flight validates the whole input shape, BEFORE the
/// submit — fail-closed, like the video lane.
pub async fn civitai_music_submit(
    _user_id: &str,
    bearer: &str,
    req: MusicGenRequest,
) -> Result<MusicSubmitView, String> {
    let key = require_key()?;
    let params = finalize_request(&req).await?;
    let est = civitai::whatif_music_gen(&key, &params).await?;
    debit_media_tokens(bearer, buzz_to_tokens(est.total_buzz)).await?;
    let submitted = civitai::submit_music_gen(&key, &params).await?;
    Ok(MusicSubmitView {
        workflow_id: submitted.id,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MusicStatusView {
    pub workflow_id: String,
    /// Same normalization as the video lane: `queued` | `processing` |
    /// `succeeded` | `failed` | `expired` | `canceled`.
    pub status: String,
    pub queue_position: Option<i64>,
    /// Signed, EXPIRING audio URL — `civitai_music_fetch` must be called on
    /// `succeeded` before it lapses.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_url: Option<String>,
    pub error: Option<String>,
}

/// Poll one music workflow (server-side long-poll, default 15s hold).
pub async fn civitai_music_status(
    workflow_id: String,
    wait_secs: Option<u64>,
) -> Result<MusicStatusView, String> {
    if workflow_id.trim().is_empty() {
        return Err("workflowId kosong".into());
    }
    let key = require_key()?;
    let wf = civitai::music_workflow_status(&key, workflow_id.trim(), wait_secs.unwrap_or(15))
        .await?;
    let status = match wf.status.as_str() {
        "unassigned" | "preparing" | "scheduled" => "queued".to_string(),
        other => other.to_string(),
    };
    Ok(MusicStatusView {
        workflow_id: wf.id,
        queue_position: wf.queue_position,
        audio_url: wf.audio.map(|a| a.url),
        error: wf.error,
        status,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedAudio {
    pub file_id: String,
    pub name: String,
}

/// Download the finished track (SIGNED, EXPIRING URL — fetch once) into the
/// office store as `ArtifactKind::Audio`. Idempotence is the CALLER's job,
/// same as the video lane.
pub async fn civitai_music_fetch(
    user_id: &str,
    workflow_id: String,
    audio_url: String,
) -> Result<SavedAudio, String> {
    let _ = require_key()?; // same baked identity; the URL itself carries the signature
    let workflow_id = workflow_id.trim().to_string();
    if workflow_id.is_empty() || audio_url.trim().is_empty() {
        return Err("workflowId dan audioUrl wajib diisi".into());
    }
    let bytes = civitai::download_bytes(audio_url.trim())
        .await
        .map_err(|e| format!("unduh audio gagal: {e}"))?;
    // Signed URLs end in the real container extension (wav/mp3/m4a/...).
    let ext = match audio_url.split('?').next().and_then(|p| {
        p.rsplit('.')
            .next()
            .map(|e| e.to_ascii_lowercase())
    }) {
        Some(e)
            if matches!(
                e.as_str(),
                "mp3" | "wav" | "m4a" | "aac" | "ogg" | "oga" | "flac"
            ) =>
        {
            e
        }
        _ => "mp3".to_string(),
    };
    let idish: String = workflow_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(12)
        .collect();
    let name = format!("civitai-music-{idish}-{}.{}", uuidish(), ext);
    let file = kawai_office::store::import_as(
        user_id,
        &name,
        &bytes,
        kawai_office::store::ArtifactKind::Audio,
        "civitai",
        None,
    )
    .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
    Ok(SavedAudio {
        file_id: file.id,
        name,
    })
}

// ── Civitai 3D MODEL generation (polyGen — workflows API) ──────────────────
//
// Same op shapes as the video/music lanes; cancel reuses
// `civitai_video_cancel` (workflow-generic PUT, same as music).

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Model3dGenRequest {
    pub ecosystem: String,
    /// meshy: "textTo3D" (default when a prompt is set) | "imageTo3D".
    #[serde(default)]
    pub process: Option<String>,
    /// meshy textTo3D prompt / hunyuan3D optional texture hint.
    #[serde(default)]
    pub prompt: Option<String>,
    /// Source image (URL / data URL / base64) for imageTo3D.
    #[serde(default)]
    pub image: Option<String>,
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub enable_prompt_expansion: Option<bool>,
    #[serde(default)]
    pub target_polycount: Option<i64>,
    #[serde(default)]
    pub topology: Option<String>,
    #[serde(default)]
    pub symmetry_mode: Option<String>,
    #[serde(default)]
    pub should_texture: Option<bool>,
    #[serde(default)]
    pub should_remesh: Option<bool>,
    #[serde(default)]
    pub enable_pbr: Option<bool>,
    #[serde(default)]
    pub texture_prompt: Option<String>,
    #[serde(default)]
    pub enable_rigging: Option<bool>,
    #[serde(default)]
    pub enable_animation: Option<bool>,
    /// tripo: "no" | "standard" | "HD".
    #[serde(default)]
    pub texture: Option<String>,
    #[serde(default)]
    pub quad: Option<bool>,
    #[serde(default)]
    pub auto_size: Option<bool>,
    #[serde(default)]
    pub face_limit: Option<i64>,
    #[serde(default)]
    pub texture_alignment: Option<String>,
    #[serde(default)]
    pub orientation: Option<String>,
    #[serde(default)]
    pub texture_seed: Option<i64>,
    /// hunyuan3D: "v2" | "v2.1" | "v2-mini".
    #[serde(default)]
    pub model_version: Option<String>,
    #[serde(default)]
    pub steps: Option<i64>,
    #[serde(default)]
    pub cfg_scale: Option<f64>,
    #[serde(default)]
    pub octree_resolution: Option<i64>,
    #[serde(default)]
    pub seed: Option<i64>,
    /// Chain the model3DPreview PNG render (default true).
    #[serde(default)]
    pub with_preview: Option<bool>,
}

impl Model3dGenRequest {
    fn to_params(&self) -> civitai::Model3dGenParams {
        civitai::Model3dGenParams {
            ecosystem: self.ecosystem.clone(),
            process: self.process.clone(),
            prompt: self.prompt.clone(),
            image: self.image.clone(),
            mode: self.mode.clone(),
            enable_prompt_expansion: self.enable_prompt_expansion,
            target_polycount: self.target_polycount,
            topology: self.topology.clone(),
            symmetry_mode: self.symmetry_mode.clone(),
            should_texture: self.should_texture,
            should_remesh: self.should_remesh,
            enable_pbr: self.enable_pbr,
            texture_prompt: self.texture_prompt.clone(),
            enable_rigging: self.enable_rigging,
            enable_animation: self.enable_animation,
            texture: self.texture.clone(),
            quad: self.quad,
            auto_size: self.auto_size,
            face_limit: self.face_limit,
            texture_alignment: self.texture_alignment.clone(),
            orientation: self.orientation.clone(),
            texture_seed: self.texture_seed,
            model_version: self.model_version.clone(),
            steps: self.steps,
            cfg_scale: self.cfg_scale,
            octree_resolution: self.octree_resolution,
            seed: self.seed,
            with_preview: self.with_preview,
        }
    }
}

/// Free cost estimate (whatif — no persist, no charge). A failure here means
/// submit would fail too: surface it as the error.
pub async fn civitai_model3d_cost(req: Model3dGenRequest) -> Result<VideoCostView, String> {
    let key = require_key()?;
    let (est, _) = civitai::whatif_model3d_gen(&key, &req.to_params()).await?;
    Ok(VideoCostView {
        total_buzz: est.total_buzz,
        total_tokens: buzz_to_tokens(est.total_buzz),
        ready: est.ready,
        warnings: est.warnings,
    })
}

/// Submit the polyGen workflow. SPENDS Buzz — the panel's Generate click
/// (with the whatif cost displayed) is the consent. The token debit rides
/// the same whatif price and happens BEFORE the submit, fail-closed like
/// the video lane. The whatif's preview-step verdict drives the submitted
/// shape, so submit can never include a step the price check rejected.
pub async fn civitai_model3d_submit(
    _user_id: &str,
    bearer: &str,
    req: Model3dGenRequest,
) -> Result<VideoSubmitView, String> {
    let key = require_key()?;
    let params = req.to_params();
    let (est, with_preview) = civitai::whatif_model3d_gen(&key, &params).await?;
    debit_media_tokens(bearer, buzz_to_tokens(est.total_buzz)).await?;
    let submitted = civitai::submit_model3d_gen(&key, &params, with_preview).await?;
    Ok(VideoSubmitView {
        workflow_id: submitted.id,
    })
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Model3dBlobView {
    pub url: String,
    /// "glb" / "fbx" when the output names the format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Model3dVariantView {
    /// "fbx" | "rigged" | "riggedFbx" | "animated" | "animatedFbx" |
    /// "walking" | "walkingFbx" | "walkingArmature" | "running" | …
    pub variant: String,
    #[serde(flatten)]
    pub blob: Model3dBlobView,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Model3dStatusView {
    pub workflow_id: String,
    /// Normalized: `queued` | `processing` | `succeeded` | `failed` |
    /// `expired` | `canceled` (anything else passes through lowercased).
    pub status: String,
    pub queue_position: Option<i64>,
    /// Primary GLB.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<Model3dBlobView>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fbx: Option<Model3dBlobView>,
    /// The chained model3DPreview render when present, else the polyGen
    /// auto-thumbnail — the result card's poster either way.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview_url: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub extras: Vec<Model3dVariantView>,
    pub error: Option<String>,
}

/// Poll one 3D workflow (server-side long-poll — the call holds up to
/// `wait_secs`, default 15, before replying with the current snapshot).
pub async fn civitai_model3d_status(
    workflow_id: String,
    wait_secs: Option<u64>,
) -> Result<Model3dStatusView, String> {
    if workflow_id.trim().is_empty() {
        return Err("workflowId kosong".into());
    }
    let key = require_key()?;
    let wf = civitai::model3d_workflow_status(&key, workflow_id.trim(), wait_secs.unwrap_or(15))
        .await?;
    let status = match wf.status.as_str() {
        "unassigned" | "preparing" | "scheduled" => "queued".to_string(),
        other => other.to_string(),
    };
    Ok(Model3dStatusView {
        workflow_id: wf.id,
        queue_position: wf.queue_position,
        model: wf.model.map(|b| Model3dBlobView {
            url: b.url,
            format: b.format,
        }),
        fbx: wf.fbx.map(|b| Model3dBlobView {
            url: b.url,
            format: b.format,
        }),
        preview_url: wf.preview.or(wf.thumbnail),
        extras: wf
            .extras
            .into_iter()
            .map(|v| Model3dVariantView {
                variant: v.variant,
                blob: Model3dBlobView {
                    url: v.blob.url,
                    format: v.blob.format,
                },
            })
            .collect(),
        error: wf.error,
        status,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedModel3d {
    /// Primary GLB.
    pub file_id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fbx_file_id: Option<String>,
    /// model3DPreview render / polyGen auto-thumbnail, stored as an image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview_file_id: Option<String>,
    /// Rigged / animated twins + the basicAnimations set, best-effort.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub additional: Vec<SavedModel3dFile>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedModel3dFile {
    pub file_id: String,
    pub name: String,
    pub variant: String,
}

/// Blob url → stored extension. Trusts the engine-declared format ("glb"/
/// "fbx"), falls back to the URL's extension, defaults glb.
fn model3d_ext(format: Option<&str>, url: &str) -> String {
    if let Some(f) = format.map(str::trim).filter(|f| !f.is_empty()) {
        let f = f.trim_start_matches('.').to_ascii_lowercase();
        if matches!(f.as_str(), "glb" | "gltf" | "fbx" | "obj" | "stl") {
            return f;
        }
    }
    match url
        .split('?')
        .next()
        .and_then(|p| p.rsplit('.').next().map(|e| e.to_ascii_lowercase()))
    {
        Some(e) if matches!(e.as_str(), "glb" | "gltf" | "fbx" | "obj" | "stl") => e,
        _ => "glb".to_string(),
    }
}

/// Download one model blob into the office store as `ArtifactKind::Model3d`.
async fn import_model3d_file(
    user_id: &str,
    workflow_id: &str,
    url: &str,
    format: Option<&str>,
    stem: &str,
) -> Result<(String, String), String> {
    let bytes = civitai::download_bytes(url.trim())
        .await
        .map_err(|e| format!("unduh model gagal: {e}"))?;
    let ext = model3d_ext(format, url);
    let idish: String = workflow_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(12)
        .collect();
    let name = format!("civitai-3d-{idish}-{stem}.{}.{}", uuidish(), ext);
    let file = kawai_office::store::import_as(
        user_id,
        &name,
        &bytes,
        kawai_office::store::ArtifactKind::Model3d,
        "civitai",
        None,
    )
    .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
    Ok((file.id, name))
}

/// Download the finished 3D model (SIGNED, EXPIRING URL — fetch once) into
/// the office store: primary GLB + FBX twin + the preview PNG + the rigged /
/// animated extras (best-effort). Idempotence is the CALLER's job: poll
/// status, and call fetch exactly once per workflow.
pub async fn civitai_model3d_fetch(
    user_id: &str,
    workflow_id: String,
    model_url: String,
    model_format: Option<String>,
    fbx_url: Option<String>,
    fbx_format: Option<String>,
    preview_url: Option<String>,
    extra_urls: Vec<Model3dVariantView>,
) -> Result<SavedModel3d, String> {
    let _ = require_key()?; // same baked identity; the URL itself carries the signature
    let workflow_id = workflow_id.trim().to_string();
    if workflow_id.is_empty() || model_url.trim().is_empty() {
        return Err("workflowId dan modelUrl wajib diisi".into());
    }
    let (file_id, name) =
        import_model3d_file(user_id, &workflow_id, model_url.trim(), model_format.as_deref(), "primary")
            .await?;
    let fbx_file_id = match fbx_url.as_deref().map(str::trim).filter(|u| !u.is_empty()) {
        Some(url) => match import_model3d_file(user_id, &workflow_id, url, fbx_format.as_deref(), "fbx").await {
            Ok((id, _)) => Some(id),
            Err(e) => {
                eprintln!("civitai: fbx unduh gagal: {e}");
                None
            }
        },
        None => None,
    };
    let preview_file_id = match preview_url.as_deref().map(str::trim).filter(|u| !u.is_empty()) {
        Some(url) => match civitai::download_bytes(url).await {
            Ok(bytes) => {
                let idish: String = workflow_id
                    .chars()
                    .filter(|c| c.is_ascii_alphanumeric())
                    .take(12)
                    .collect();
                let tname = format!("civitai-3d-{idish}-preview.{}.png", uuidish());
                match kawai_office::store::import_as(
                    user_id,
                    &tname,
                    &bytes,
                    kawai_office::store::ArtifactKind::Image,
                    "civitai",
                    None,
                ) {
                    Ok(file) => Some(file.id),
                    Err(e) => {
                        eprintln!("civitai: preview simpan gagal: {e}");
                        None
                    }
                }
            }
            // Preview is best-effort — the result card falls back to a
            // generic 3D tile when the render is missing.
            Err(e) => {
                eprintln!("civitai: preview unduh gagal: {e}");
                None
            }
        },
        None => None,
    };
    // Rigged / animated twins + basicAnimations: import after the primary;
    // a failed extra is logged, not fatal.
    let mut additional = Vec::new();
    for extra in extra_urls {
        if extra.blob.url.trim().is_empty() {
            continue;
        }
        match import_model3d_file(
            user_id,
            &workflow_id,
            extra.blob.url.trim(),
            extra.blob.format.as_deref(),
            &variant_stem(&extra.variant),
        )
        .await
        {
            Ok((id, name)) => additional.push(SavedModel3dFile {
                file_id: id,
                name,
                variant: extra.variant,
            }),
            Err(e) => eprintln!("civitai: varian {} gagal: {e}", extra.variant),
        }
    }
    Ok(SavedModel3d {
        file_id,
        name,
        fbx_file_id,
        preview_file_id,
        additional,
    })
}

/// File-stem-safe variant tag (parser variants are already `[A-Za-z]`; this
/// is belt-and-suspenders against future wire values).
fn variant_stem(variant: &str) -> String {
    variant
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect()
}

#[cfg(test)]
mod model3d_tests {
    use super::*;

    /// The panel's flat camelCase request maps 1:1 onto the crate's params
    /// (offline — validate/whatif never touch the vault on the shape path).
    #[test]
    fn model3d_request_maps_to_params() {
        let req = Model3dGenRequest {
            ecosystem: "meshy".into(),
            process: Some("textTo3D".into()),
            prompt: Some("a dragon statue".into()),
            image: None,
            mode: None,
            enable_prompt_expansion: None,
            target_polycount: Some(50_000),
            topology: Some("quad".into()),
            symmetry_mode: None,
            should_texture: None,
            should_remesh: None,
            enable_pbr: Some(true),
            texture_prompt: None,
            enable_rigging: None,
            enable_animation: Some(true),
            texture: None,
            quad: None,
            auto_size: None,
            face_limit: None,
            texture_alignment: None,
            orientation: None,
            texture_seed: None,
            model_version: None,
            steps: None,
            cfg_scale: None,
            octree_resolution: None,
            seed: Some(42),
            with_preview: None,
        };
        let params = req.to_params();
        assert_eq!(params.ecosystem, "meshy");
        assert_eq!(params.process.as_deref(), Some("textTo3D"));
        assert_eq!(params.target_polycount, Some(50_000));
        assert_eq!(params.enable_animation, Some(true));
        assert_eq!(params.seed, Some(42));
        params.validate().expect("meshy txt shape validates");
    }

    /// Extension derivation trusts the engine-declared format, falls back
    /// to the URL path, defaults glb.
    #[test]
    fn model3d_ext_precedence() {
        assert_eq!(model3d_ext(Some("glb"), "https://x/y.fbx?sig=1"), "glb");
        assert_eq!(model3d_ext(Some("FBX"), "https://x/y"), "fbx");
        assert_eq!(model3d_ext(Some(".fbx"), "https://x/y"), "fbx");
        assert_eq!(model3d_ext(None, "https://x/y.FBX?sig=1"), "fbx");
        assert_eq!(model3d_ext(None, "https://x/blob"), "glb");
        assert_eq!(model3d_ext(Some("weird"), "https://x/blob"), "glb");
    }
}

#[cfg(test)]
mod music_tests {
    use super::*;

    /// The panel sends Sonilo's single prompt as `prompt`; the crate carries
    /// it in `caption`. Regression guard for the mapping (offline — the
    /// sonilo path never drafts and never touches the vault).
    #[tokio::test]
    async fn sonilo_prompt_maps_to_caption() {
        let params = finalize_request(&MusicGenRequest {
            ecosystem: "sonilo".into(),
            mode: Some("custom".into()),
            operation: Some("soundEffect".into()),
            prompt: Some("glass shatter".into()),
            caption: None,
            lyrics: None,
            abc: None,
            score_mode: None,
            steps: None,
            bpm: None,
            key: None,
            instrumental_weight: None,
            vocal_weight: None,
            cfg_scale: None,
            model: None,
            cover_image: None,
            duration: Some(2.5),
            seed: None,
        })
        .await
        .unwrap();
        assert_eq!(params.caption.as_deref(), Some("glass shatter"));
        assert_eq!(params.operation.as_deref(), Some("soundEffect"));

        // API-style callers that put the prompt in `caption` still work.
        let params = finalize_request(&MusicGenRequest {
            ecosystem: "sonilo".into(),
            mode: Some("custom".into()),
            operation: Some("music".into()),
            prompt: None,
            caption: Some("lofi beat".into()),
            lyrics: None,
            abc: None,
            score_mode: None,
            steps: None,
            bpm: None,
            key: None,
            instrumental_weight: None,
            vocal_weight: None,
            cfg_scale: None,
            model: None,
            cover_image: None,
            duration: Some(60.0),
            seed: None,
        })
        .await
        .unwrap();
        assert_eq!(params.caption.as_deref(), Some("lofi beat"));
    }
}

#[cfg(test)]
mod pricing_tests {
    use super::*;

    /// 8 Buzz (1024², 25 steps, 1 qty) = the docs' base charge → 19.200
    /// tokens at TOKENS_PER_BUZZ 2.400; fractional Buzz always rounds UP.
    #[test]
    fn buzz_conversion_ceil() {
        assert_eq!(buzz_to_tokens(8.0), 19_200);
        assert_eq!(buzz_to_tokens(0.5), 1_200);
        assert_eq!(buzz_to_tokens(0.001), 3); // 2.4 → ceil 3
        assert_eq!(buzz_to_tokens(0.0), 0);
    }

    fn params(workflow: Option<&str>, w: i64, h: i64, steps: Option<i64>, qty: Option<i64>) -> ImageGenParams {
        ImageGenParams {
            ecosystem: "anima".into(),
            engine: None,
            workflow: workflow.map(str::to_string),
            prompt: "x".into(),
            source_image: None,
            strength: None,
            upscale_repeats: None,
            negative_prompt: None,
            width: w,
            height: h,
            cfg_scale: None,
            steps,
            quantity: qty,
            seed: None,
            loras: Vec::new(),
            diffuser_model: None,
            sampler: None,
            clip_skip: None,
        }
    }

    /// Base charge: 8 Buzz at 1024²/25/1 — the docs' reference job.
    #[test]
    fn image_base_gen() {
        let est = image_buzz_estimate(&params(Some("txt2img"), 1024, 1024, Some(25), Some(1)));
        assert!((est - 8.0).abs() < 1e-9, "{est}");
    }

    /// txt2img defaults: steps None → 30 (the panel's default, 1.2× base),
    /// workflow None = txt2img.
    #[test]
    fn image_defaults() {
        let est = image_buzz_estimate(&params(None, 1024, 1024, None, None));
        assert!((est - 9.6).abs() < 1e-9, "{est}");
    }

    /// hires-fix = generation + one upscale pass at doubled dims (4× unit).
    #[test]
    fn image_hires_fix_doubles() {
        let est = image_buzz_estimate(&params(Some("txt2img:hires-fix"), 1024, 1024, Some(25), Some(1)));
        assert!((est - 40.0).abs() < 1e-9, "{est}"); // 8 + 4×8
    }

    /// img2img:upscale = passes only (no generation step billed).
    #[test]
    fn image_upscale_passes_only() {
        let est = image_buzz_estimate(&params(Some("img2img:upscale"), 1024, 1024, Some(25), Some(1)));
        assert!((est - 32.0).abs() < 1e-9, "{est}"); // 1 pass × 4×8
    }
}
