//! Civitai image generation — Generator panel ops (both transports).
//!
//! Pure layer — `reqwest` + the `civitai` client crate only, no tauri/axum:
//! BOTH transports (Tauri commands in `commands.rs`, Axum routes in `web.rs`)
//! call these same fns. Identity (`user_id`) is resolved at the transport
//! edge and passed in — the frontend never sends it.
//!
//! Credential model: the Civitai API key is product-baked in
//! `kawai-vault/constants` (`civitai::get_civitai()`, generated by the
//! vault's gen crate). Empty getter = generation unconfigured.
//!
//! Flow: `civitai_generate` submits the recipe endpoint (spends Buzz — the
//! job itself is asynchronous, so the `civitai` client long-polls `?wait=90`
//! and keeps polling the workflow until it turns terminal before returning)
//! then downloads the signed expiring blob URLs and lands the files in the
//! office store (`source_tool: "civitai"`) — they render anywhere
//! `kawai-file://` tokens render. Cost display is the docs' pricing formula
//! computed client-side (the API has no free pricing mode — verified live).

use serde::{Deserialize, Serialize};
use std::sync::{LazyLock, Mutex};
use std::time::{Duration, Instant};

use civitai::{Blob, ImageGenParams};

// ── Wire types (camelCase both directions, like logic::topup) ──────────────

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiKeyStatus {
    pub configured: bool,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedImage {
    pub file_id: String,
    pub name: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelCover {
    pub ecosystem: String,
    pub label: String,
    /// The model's card art on civitai (CDN URL) — None when the lookup
    /// found nothing; the UI falls back to the gradient tile.
    pub url: Option<String>,
    pub model_name: Option<String>,
}

/// Top-checkpoint cover art per panel ecosystem (the thing that makes the
/// picker look like civitai's). Public v1 read; cached in-process for 1h —
/// the picker hits this on every panel mount. Cover art rides the LIST
/// payload (`modelVersions[0].images`) — no per-model image calls.
static COVER_CACHE: LazyLock<Mutex<Option<(Instant, Vec<ModelCover>)>>> =
    LazyLock::new(|| Mutex::new(None));
const COVER_TTL: Duration = Duration::from_secs(3600);
/// Panel ecosystem → v1 search query (top Checkpoint by rating).
const COVER_QUERIES: [(&str, &str); 4] = [
    ("anima", "anime"),
    ("sdxl", "sdxl"),
    ("flux1", "flux"),
    ("flux2Klein", "flux klein"),
];

pub async fn civitai_model_covers() -> Result<Vec<ModelCover>, String> {
    if let Some((at, covers)) = COVER_CACHE.lock().ok().and_then(|c| c.clone()) {
        if at.elapsed() < COVER_TTL {
            return Ok(covers);
        }
    }

    let key = kawai_constants::civitai::get_civitai();
    let mut covers = Vec::with_capacity(COVER_QUERIES.len());
    for (ecosystem, query) in COVER_QUERIES {
        let cover = civitai::search_models(&key, query, &["Checkpoint"], 3, Some("Highest Rated"), None)
            .await
            .ok()
            .and_then(|page| {
                page.items.into_iter().find_map(|m| {
                    let url = m
                        .model_versions
                        .as_ref()?
                        .first()?
                        .images
                        .as_ref()?
                        .first()?
                        .url
                        .clone()?;
                    Some(ModelCover {
                        ecosystem: ecosystem.to_string(),
                        label: ecosystem.to_string(),
                        url: Some(url),
                        model_name: Some(m.name),
                    })
                })
            });
        covers.push(cover.unwrap_or(ModelCover {
            ecosystem: ecosystem.to_string(),
            label: ecosystem.to_string(),
            url: None,
            model_name: None,
        }));
    }
    if let Ok(mut c) = COVER_CACHE.lock() {
        *c = Some((Instant::now(), covers.clone()));
    }
    Ok(covers)
}

// ── Resource browser (the civitai model-picker modal) ──────────────────────

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelsArgs {
    /// Target generation ecosystem — the constructed AIR URN carries it,
    /// and rows whose v1 `baseModel` maps to a DIFFERENT known family are
    /// dropped (both sides unclassified = kept, the orchestrator decides).
    pub ecosystem: String,
    #[serde(default)]
    pub query: Option<String>,
    /// `"Checkpoint"` (default) or `"LORA"`.
    #[serde(default)]
    pub model_type: Option<String>,
    /// v1 sort: `"Highest Rated"` (default) | `"Most Downloaded"` | `"Newest"`.
    #[serde(default)]
    pub sort: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
    /// Keyset cursor from the previous page (`nextCursor`) — None = page 1.
    #[serde(default)]
    pub cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelPage {
    pub rows: Vec<SearchModelRow>,
    /// None = no more pages.
    pub next_cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchModelRow {
    pub model_id: i64,
    pub version_id: i64,
    pub name: String,
    pub creator: Option<String>,
    pub downloads: Option<i64>,
    pub thumbs_up: Option<i64>,
    pub base_model: Option<String>,
    pub cover_url: Option<String>,
    /// HTML description stripped to plain text, capped for the grid card.
    pub description: Option<String>,
    /// Up to 3 showcase images BESIDES the cover — the example strip.
    pub example_urls: Vec<String>,
    /// `urn:air:{ecosystem}:{checkpoint|lora}:civitai:{model}@{version}` —
    /// constructed; list payloads do not carry AIR URNs.
    pub air_urn: String,
}

/// Crude HTML→text (tag stripping + whitespace collapse) — descriptions are
/// display-only snippets, never rendered as HTML.
fn strip_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for ch in s.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            c if !in_tag => out.push(c),
            _ => {}
        }
    }
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn truncate_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let cut: String = s.chars().take(max).collect();
    format!("{cut}…")
}

pub async fn civitai_search_models(args: SearchModelsArgs) -> Result<SearchModelPage, String> {
    let key = require_key()?;
    let is_lora = matches!(args.model_type.as_deref(), Some("LORA") | Some("lora"));
    let model_type = if is_lora { "LORA" } else { "Checkpoint" };
    let limit = args.limit.unwrap_or(20).clamp(1, 50);
    let page = civitai::search_models(
        &key,
        args.query.as_deref().unwrap_or(""),
        &[model_type],
        limit,
        args.sort.as_deref(),
        args.cursor.as_deref(),
    )
    .await?;
    let next_cursor = page.next_cursor();
    let eco_family = civitai::registry::ecosystem_family(&args.ecosystem);
    let rows = page
        .items
        .into_iter()
        .filter_map(|m| {
            let version = m.model_versions.as_ref()?.first()?;
            let creator = m.creator.and_then(|c| c.username);
            let downloads = m.stats.as_ref().and_then(|s| s.download_count);
            let thumbs_up = m.stats.as_ref().and_then(|s| s.thumbs_up_count);
            // Cover/examples usually ride the FIRST version — but some models
            // only have showcase art on older versions, so scan until found.
            let images = m
                .model_versions
                .as_ref()
                .and_then(|versions| {
                    versions
                        .iter()
                        .find(|v| v.images.as_ref().is_some_and(|imgs| !imgs.is_empty()))
                        .or_else(|| versions.first())
                })
                .and_then(|v| v.images.as_ref())
                .map(|imgs| imgs.iter().filter_map(|i| i.url.clone()).collect::<Vec<_>>())
                .unwrap_or_default();
            let cover_url = images.first().cloned();
            // Example strip: up to 3 showcase images besides the cover.
            let example_urls: Vec<String> = images.into_iter().skip(1).take(3).collect();
            let description = m
                .description
                .as_deref()
                .map(strip_html)
                .filter(|s| !s.is_empty())
                .map(|s| truncate_chars(&s, 220));
            Some(SearchModelRow {
                model_id: m.id,
                version_id: version.id,
                air_urn: format!(
                    "urn:air:{}:{}:civitai:{}@{}",
                    args.ecosystem, kind_segment(is_lora), m.id, version.id
                ),
                name: m.name,
                creator,
                downloads,
                thumbs_up,
                base_model: version.base_model.clone(),
                cover_url,
                description,
                example_urls,
            })
        })
        // Model follows ecosystem: drop rows whose base model maps to a
        // different KNOWN family (either side unclassified = kept — the
        // orchestrator, not a prefix table, has the last word).
        .filter(|row| match (
            eco_family,
            row.base_model
                .as_deref()
                .and_then(civitai::registry::base_model_family),
        ) {
            (Some(a), Some(b)) => a == b,
            _ => true,
        })
        .collect();
    Ok(SearchModelPage {
        rows,
        next_cursor,
    })
}

fn kind_segment(is_lora: bool) -> &'static str {
    if is_lora {
        "lora"
    } else {
        "checkpoint"
    }
}

// ── API key ────────────────────────────────────────────────────────────────

fn require_key() -> Result<String, String> {
    let key = kawai_constants::civitai::get_civitai();
    if key.trim().is_empty() {
        return Err(
            "Civitai API key belum dikonfigurasi di vault (kawai-vault/constants)".to_string(),
        );
    }
    Ok(key)
}

pub fn civitai_api_key_status() -> ApiKeyStatus {
    ApiKeyStatus {
        configured: !kawai_constants::civitai::get_civitai().trim().is_empty(),
    }
}

// ── Generation ─────────────────────────────────────────────────────────────

fn blob_view(b: &Blob) -> Option<&Blob> {
    b.url
        .as_ref()
        .is_some_and(|u| !u.trim().is_empty())
        .then_some(b)
}

/// Generate images and persist them into the user's office store. The
/// recipe call is synchronous (10–25s at spec defaults; minutes for large
/// batches) and SPENDS Buzz — the panel's Generate click is the consent.
/// Each call creates NEW files (import semantics).
pub async fn civitai_generate(
    user_id: &str,
    params: ImageGenParams,
) -> Result<Vec<SavedImage>, String> {
    let key = require_key()?;
    let result = civitai::submit_image_gen(&key, &params).await?;
    if result.images.is_empty() {
        return Err(result
            .errors
            .and_then(|errs| errs.into_iter().next())
            .unwrap_or_else(|| "Civitai tidak mengembalikan gambar".into()));
    }
    let short_id: String = params.ecosystem.clone() + "-" + &uuidish();
    let mut saved = Vec::with_capacity(result.images.len());
    let mut failed_downloads: Vec<String> = Vec::new();
    for (i, blob) in result.images.iter().filter_map(blob_view).enumerate() {
        let url = blob.url.as_deref().unwrap_or_default();
        let bytes = match civitai::download_bytes(url).await {
            Ok(bytes) => bytes,
            Err(e) => {
                failed_downloads.push(format!("gambar {}: {e}", i + 1));
                continue;
            }
        };
        // Signed URLs end in the real extension (.jpeg/.png); default jpg.
        let ext = if url.split('?').next().is_some_and(|p| p.ends_with(".png")) {
            "png"
        } else {
            "jpg"
        };
        let name = format!("civitai-{short_id}-{}.{}", i + 1, ext);
        let file = kawai_office::store::import_as(
            user_id,
            &name,
            &bytes,
            kawai_office::store::ArtifactKind::Image,
            "civitai",
            None,
        )
        .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
        saved.push(SavedImage {
            file_id: file.id,
            name,
        });
    }
    if saved.is_empty() {
        return Err(format!(
            "semua unduhan gagal: {}",
            failed_downloads.join("; ")
        ));
    }
    if !failed_downloads.is_empty() {
        eprintln!("civitai: {} unduhan gagal", failed_downloads.join("; "));
    }
    Ok(saved)
}

/// Short per-run discriminator for file names (timestamp-based; the office
/// store mints its own opaque ids — this only keeps names readable).
fn uuidish() -> String {
    let d = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    format!("{d:x}")
}

// ── Video generation (workflows API) ───────────────────────────────────────
//
// Video runs through the ASYNC workflow surface, not the synchronous recipe:
// submit spends Buzz and returns a workflowId; the panel polls
// `civitai_video_status` (server-side long-poll) until a terminal state,
// then `civitai_video_fetch` downloads the signed mp4 ONCE into the office
// store. Restart-safe by design — the workflowId lives client-side, and
// status/fetch are idempotent reads; nothing generation-shaped lives in
// memory between calls.

/// Panel request shape — camelCase from both transports, mapped onto the
/// client's `VideoGenParams`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoGenRequest {
    pub ecosystem: String,
    #[serde(default)]
    pub workflow: Option<String>,
    #[serde(default)]
    pub prompt: Option<String>,
    #[serde(default)]
    pub negative_prompt: Option<String>,
    #[serde(default)]
    pub source_image: Option<String>,
    #[serde(default)]
    pub end_image: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub fast_mode: Option<bool>,
    #[serde(default)]
    pub duration: Option<i64>,
    #[serde(default)]
    pub resolution: Option<String>,
    #[serde(default)]
    pub aspect_ratio: Option<String>,
    #[serde(default)]
    pub generate_audio: Option<bool>,
    #[serde(default)]
    pub enable_prompt_enhancer: Option<bool>,
    #[serde(default)]
    pub cfg_scale: Option<f64>,
    #[serde(default)]
    pub seed: Option<i64>,
    #[serde(default)]
    pub quantity: Option<i64>,
}

impl VideoGenRequest {
    fn to_params(&self) -> civitai::VideoGenParams {
        civitai::VideoGenParams {
            ecosystem: self.ecosystem.clone(),
            workflow: self.workflow.clone(),
            prompt: self.prompt.clone().unwrap_or_default(),
            negative_prompt: self.negative_prompt.clone(),
            source_image: self.source_image.clone(),
            end_image: self.end_image.clone(),
            model: self.model.clone(),
            mode: self.mode.clone(),
            fast_mode: self.fast_mode,
            duration: self.duration,
            resolution: self.resolution.clone(),
            aspect_ratio: self.aspect_ratio.clone(),
            generate_audio: self.generate_audio,
            enable_prompt_enhancer: self.enable_prompt_enhancer,
            cfg_scale: self.cfg_scale,
            seed: self.seed,
            quantity: self.quantity,
        }
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoCostView {
    pub total_buzz: f64,
    pub ready: bool,
    pub warnings: Vec<String>,
}

/// Free cost estimate (whatif — no persist, no charge). A failure here means
/// submit would fail too: surface it as the error.
pub async fn civitai_video_cost(req: VideoGenRequest) -> Result<VideoCostView, String> {
    let key = require_key()?;
    let est = civitai::whatif_video_gen(&key, &req.to_params()).await?;
    Ok(VideoCostView {
        total_buzz: est.total_buzz,
        ready: est.ready,
        warnings: est.warnings,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoSubmitView {
    pub workflow_id: String,
}

/// Submit the videoGen workflow. SPENDS Buzz — the panel's Generate click
/// (with the whatif cost displayed) is the consent. Returns the workflowId
/// the panel stores and polls.
pub async fn civitai_video_submit(
    _user_id: &str,
    req: VideoGenRequest,
) -> Result<VideoSubmitView, String> {
    let key = require_key()?;
    let submitted = civitai::submit_video_gen(&key, &req.to_params()).await?;
    Ok(VideoSubmitView {
        workflow_id: submitted.id,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoBlobView {
    pub video_url: String,
    pub thumbnail_url: Option<String>,
    pub width: Option<i64>,
    pub height: Option<i64>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoStatusView {
    pub workflow_id: String,
    /// Normalized: `queued` | `processing` | `succeeded` | `failed` |
    /// `expired` | `canceled` (anything else passes through lowercased).
    pub status: String,
    pub queue_position: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video: Option<VideoBlobView>,
    pub error: Option<String>,
}

/// Poll one workflow (server-side long-poll — the call holds up to
/// `wait_secs`, default 15, before replying with the current snapshot).
pub async fn civitai_video_status(
    workflow_id: String,
    wait_secs: Option<u64>,
) -> Result<VideoStatusView, String> {
    if workflow_id.trim().is_empty() {
        return Err("workflowId kosong".into());
    }
    let key = require_key()?;
    let wf = civitai::video_workflow_status(&key, workflow_id.trim(), wait_secs.unwrap_or(15))
        .await?;
    let status = match wf.status.as_str() {
        "unassigned" | "preparing" | "scheduled" => "queued".to_string(),
        other => other.to_string(),
    };
    Ok(VideoStatusView {
        workflow_id: wf.id,
        queue_position: wf.queue_position,
        video: wf.video_url.map(|video_url| VideoBlobView {
            video_url,
            thumbnail_url: wf.thumbnail_url,
            width: wf.width,
            height: wf.height,
        }),
        error: wf.error,
        status,
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SavedVideo {
    pub file_id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail_file_id: Option<String>,
}

/// Download the finished video (SIGNED, EXPIRING URL — fetch once) into the
/// office store as `ArtifactKind::Video`, plus its poster thumbnail as an
/// image. Idempotence is the CALLER's job: poll status, and call fetch
/// exactly once per workflow (re-fetching would duplicate files — import
/// semantics always create new entries).
pub async fn civitai_video_fetch(
    user_id: &str,
    workflow_id: String,
    video_url: String,
    thumbnail_url: Option<String>,
) -> Result<SavedVideo, String> {
    let _ = require_key()?; // same baked identity; the URL itself carries the signature
    let workflow_id = workflow_id.trim().to_string();
    if workflow_id.is_empty() || video_url.trim().is_empty() {
        return Err("workflowId dan videoUrl wajib diisi".into());
    }
    let bytes = civitai::download_bytes(video_url.trim())
        .await
        .map_err(|e| format!("unduh video gagal: {e}"))?;
    // Signed URLs end in the real extension; videos are mp4 almost always,
    // webm occasionally.
    let ext = match video_url.split('?').next().and_then(|p| {
        p.rsplit('.')
            .next()
            .map(|e| e.to_ascii_lowercase())
    }) {
        Some(e) if e == "webm" || e == "mov" || e == "m4v" => e,
        _ => "mp4".to_string(),
    };
    let idish: String = workflow_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(12)
        .collect();
    let name = format!("civitai-video-{idish}-{}.{}", uuidish(), ext);
    let file = kawai_office::store::import_as(
        user_id,
        &name,
        &bytes,
        kawai_office::store::ArtifactKind::Video,
        "civitai",
        None,
    )
    .map_err(|e| format!("gagal menyimpan {name}: {e}"))?;
    let mut thumbnail_file_id = None;
    if let Some(thumb) = thumbnail_url.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
        match civitai::download_bytes(thumb).await {
            Ok(bytes) => {
                let tname = format!("civitai-video-{idish}-thumb.jpg");
                if let Ok(file) = kawai_office::store::import_as(
                    user_id,
                    &tname,
                    &bytes,
                    kawai_office::store::ArtifactKind::Image,
                    "civitai",
                    None,
                ) {
                    thumbnail_file_id = Some(file.id);
                }
            }
            // Poster is best-effort — the <video> element renders its own
            // first frame when the thumbnail is missing.
            Err(e) => eprintln!("civitai: thumbnail unduh gagal: {e}"),
        }
    }
    Ok(SavedVideo {
        file_id: file.id,
        name,
        thumbnail_file_id,
    })
}
