// Code generated by rig-tools-gen --category=finance; DO NOT EDIT.

//! Generated tools grouped by URL host `alphavantage`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStockQuoteArgs {
    pub symbol: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetStockQuoteTool {
    base: ToolBase,
}

impl GetStockQuoteTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStockQuoteTool {
    const NAME: &'static str = "get_stock_quote";
    type Args = GetStockQuoteArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the latest stock quote for a symbol. Returns open, high, low, price, volume, previous close, change, and change percent. Use when the user asks about a stock's current price or daily performance.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker symbol. Examples: \"AAPL\" (Apple), \"TSLA\" (Tesla), \"GOOGL\" (Google), \"MSFT\" (Microsoft), \"AMZN\" (Amazon)." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={symbol}&apikey=$ALPHAVANTAGE_API_KEYS",
            headers: None,
            defaults: None,
        }, map).await
    }
}
