// Code generated by rig-tools-gen --category=finance; DO NOT EDIT.

//! Generated tools grouped by URL host `binance`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCryptoKlinesArgs {
    pub symbol: String,
    #[serde(default)]
    pub interval: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCryptoKlinesTool {
    base: ToolBase,
}

impl GetCryptoKlinesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCryptoKlinesTool {
    const NAME: &'static str = "get_crypto_klines";
    type Args = GetCryptoKlinesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get historical OHLCV candlestick data for a crypto trading pair. Returns open, high, low, close, and volume per time interval. Use for technical analysis, price history, trend and volatility analysis over time. Read-only market data, not for trading.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Crypto trading pair symbol, uppercase with no separator: base asset followed by quote asset. Examples: \"BTCUSDT\", \"ETHUSDT\", \"SOLUSDT\", \"BNBUSDT\". Quote asset is usually USDT." },
                "interval": { "type": "string", "description": "Candle interval. One of: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M. Default is \"1d\"." },
                "limit": { "type": "integer", "description": "Number of candles to return (max 1000). Default is 100." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://data-api.binance.vision/api/v3/klines?symbol={symbol}&interval={interval}&limit={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("interval", serde_json::json!("1d")),
                ("limit", serde_json::json!(100)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCryptoTicker24hrArgs {
    pub symbol: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetCryptoTicker24hrTool {
    base: ToolBase,
}

impl GetCryptoTicker24hrTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCryptoTicker24hrTool {
    const NAME: &'static str = "get_crypto_ticker_24hr";
    type Args = GetCryptoTicker24hrArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get 24-hour rolling price change statistics for a crypto trading pair: price change and percent change, high, low, weighted average price, base volume, and quote volume. Use for volatility and liquidity analysis.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Crypto trading pair symbol, uppercase with no separator. Examples: \"BTCUSDT\", \"ETHUSDT\", \"SOLUSDT\"." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://data-api.binance.vision/api/v3/ticker/24hr?symbol={symbol}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCryptoOrderbookArgs {
    pub symbol: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCryptoOrderbookTool {
    base: ToolBase,
}

impl GetCryptoOrderbookTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCryptoOrderbookTool {
    const NAME: &'static str = "get_crypto_orderbook";
    type Args = GetCryptoOrderbookArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the current order book (bid and ask depth) for a crypto trading pair. Returns price levels and quantities on both sides. Use for market depth and liquidity analysis. Read-only, not for placing orders.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Crypto trading pair symbol, uppercase with no separator. Examples: \"BTCUSDT\", \"ETHUSDT\"." },
                "limit": { "type": "integer", "description": "Number of price levels per side. One of: 5, 10, 20, 50, 100, 500, 1000. Default is 50." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://data-api.binance.vision/api/v3/depth?symbol={symbol}&limit={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(50)),
            ])),
        }, map).await
    }
}
