// Code generated by rig-tools-gen --category=finance; DO NOT EDIT.

//! Generated tools grouped by URL host `coingecko`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCryptoPriceArgs {
    pub coin_ids: String,
    #[serde(default)]
    pub vs_currency: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCryptoPriceTool {
    base: ToolBase,
}

impl GetCryptoPriceTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCryptoPriceTool {
    const NAME: &'static str = "get_crypto_price";
    type Args = GetCryptoPriceArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get current price of cryptocurrencies in USD and IDR (or other currencies). Returns price for one or multiple coins. Use when the user asks about crypto prices, how much Bitcoin costs, or wants to check a coin's current value.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "coin_ids": { "type": "string", "description": "Comma-separated coin IDs. Examples: \"bitcoin\", \"ethereum,solana,cardano\", \"dogecoin\", \"ripple\". Use lowercase IDs from CoinGecko." },
                "vs_currency": { "type": "string", "description": "Target currency. Examples: \"usd\", \"idr\", \"eur\", \"gbp\", \"jpy\". Default is \"usd\"." },
            },
            "required": [
                "coin_ids",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies={vs_currency}",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCryptoMarketArgs {
    #[serde(default)]
    pub vs_currency: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCryptoMarketTool {
    base: ToolBase,
}

impl GetCryptoMarketTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCryptoMarketTool {
    const NAME: &'static str = "get_crypto_market";
    type Args = GetCryptoMarketArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get top cryptocurrencies by market cap with price, 24h change, volume, market cap, and all-time high. Use when the user asks about the crypto market overview, top coins, or wants detailed market data.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "vs_currency": { "type": "string", "description": "Target currency. Examples: \"usd\", \"idr\". Default is \"usd\"." },
                "limit": { "type": "integer", "description": "Number of coins. Default is 10." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.coingecko.com/api/v3/coins/markets?vs_currency={vs_currency}&order=market_cap_desc&per_page={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(10)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchCryptoArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchCryptoTool {
    base: ToolBase,
}

impl SearchCryptoTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchCryptoTool {
    const NAME: &'static str = "search_crypto";
    type Args = SearchCryptoArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for a cryptocurrency by name or symbol. Returns coin ID, name, symbol, and market cap rank. Use when the user mentions a coin and you need to find its ID for further queries.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search term. Examples: \"bitcoin\", \"doge\", \"sol\", \"cardano\", \"bnb\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.coingecko.com/api/v3/search?query={query}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
