// Code generated by rig-tools-gen --category=finance; DO NOT EDIT.

//! Generated tools grouped by URL host `frankfurter`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CurrencyExchangeArgs {
    pub currency_symbol: String,
}

#[derive(Debug, Clone, Default)]
pub struct CurrencyExchangeTool {
    base: ToolBase,
}

impl CurrencyExchangeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for CurrencyExchangeTool {
    const NAME: &'static str = "currency_exchange";
    type Args = CurrencyExchangeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Convert an amount from one currency to another using current European Central Bank exchange rates. Use when the user asks about exchange rates, currency conversion, or how much something costs in another currency.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "currency_symbol": { "type": "string", "description": "Three-letter ISO 4217 currency code to convert to from USD. Examples: EUR, GBP, JPY, CAD, AUD, CHF, CNY, IDR." },
            },
            "required": [
                "currency_symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl:
                        "https://api.frankfurter.dev/v1/latest?base=USD&symbols={currency_symbol}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSupportedCurrenciesArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetSupportedCurrenciesTool {
    base: ToolBase,
}

impl GetSupportedCurrenciesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSupportedCurrenciesTool {
    const NAME: &'static str = "get_supported_currencies";
    type Args = GetSupportedCurrenciesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the full list of supported currency codes and their names for exchange rate conversion. Use when the user asks what currencies are available.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.frankfurter.dev/v1/currencies",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
