// Code generated by rig-tools-gen --category=finance; DO NOT EDIT.

//! Generated tools grouped by URL host `tiingo`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStockFundamentalsArgs {
    pub ticker: String,
    #[serde(default)]
    pub start_date: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetStockFundamentalsTool {
    base: ToolBase,
}

impl GetStockFundamentalsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStockFundamentalsTool {
    const NAME: &'static str = "get_stock_fundamentals";
    type Args = GetStockFundamentalsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get daily valuation metrics for a company: market cap, enterprise value, P/E ratio, P/B ratio, and trailing PEG. Use for fundamental / valuation analysis (is a stock cheap or expensive). Coverage is currently limited to the 30 Dow Jones components (e.g. AAPL, MSFT, JPM, KO, DIS, V, HD, MCD); other tickers are not available.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "ticker": { "type": "string", "description": "Stock ticker, a Dow Jones 30 component. Examples: \"AAPL\", \"MSFT\", \"JPM\", \"KO\", \"DIS\", \"V\", \"HD\", \"MCD\", \"CAT\", \"GS\"." },
                "start_date": { "type": "string", "description": "Optional start date (YYYY-MM-DD) to return metrics from. Omit to get the full available history (up to ~3 years). Example: \"2026-01-01\"." },
            },
            "required": [
                "ticker",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.tiingo.com/tiingo/fundamentals/{ticker}/daily?startDate={start_date}&token=$TIINGO_API_KEYS",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStockFinancialsArgs {
    pub ticker: String,
    #[serde(default)]
    pub start_date: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetStockFinancialsTool {
    base: ToolBase,
}

impl GetStockFinancialsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStockFinancialsTool {
    const NAME: &'static str = "get_stock_financials";
    type Args = GetStockFinancialsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get historical quarterly and annual financial statements for a company: income statement, balance sheet, cash flow, and derived ratios. Use for deep fundamental analysis. Coverage is currently limited to the 30 Dow Jones components (e.g. AAPL, MSFT, JPM, KO, DIS); other tickers are not available. Response can be large.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "ticker": { "type": "string", "description": "Stock ticker, a Dow Jones 30 component. Examples: \"AAPL\", \"MSFT\", \"JPM\", \"KO\", \"DIS\"." },
                "start_date": { "type": "string", "description": "Optional start date (YYYY-MM-DD) to limit how far back statements are returned. Omit for full history. Example: \"2024-01-01\"." },
            },
            "required": [
                "ticker",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.tiingo.com/tiingo/fundamentals/{ticker}/statements?startDate={start_date}&token=$TIINGO_API_KEYS",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetForexHistoryArgs {
    pub pair: String,
    #[serde(default)]
    pub start_date: Option<String>,
    #[serde(default)]
    pub resample_freq: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetForexHistoryTool {
    base: ToolBase,
}

impl GetForexHistoryTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetForexHistoryTool {
    const NAME: &'static str = "get_forex_history";
    type Args = GetForexHistoryArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get historical foreign-exchange rates (OHLC) for a currency pair over time. Use for FX trend analysis and historical exchange-rate lookups. Complements currency_exchange, which only gives the current spot rate.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "pair": { "type": "string", "description": "Currency pair, lowercase, no separator: base then quote. Examples: \"eurusd\", \"gbpusd\", \"usdjpy\", \"usdidr\", \"audusd\"." },
                "start_date": { "type": "string", "description": "Start date (YYYY-MM-DD) for the history. Example: \"2026-01-01\". Recommended to keep the response bounded." },
                "resample_freq": { "type": "string", "description": "Sampling frequency: 1day, 1hour, 5min, 1min. Default is \"1day\"." },
            },
            "required": [
                "pair",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.tiingo.com/tiingo/fx/{pair}/prices?startDate={start_date}&resampleFreq={resample_freq}&token=$TIINGO_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("resample_freq", serde_json::json!("1day")),
            ])),
        }, map).await
    }
}
