// Code generated by rig-tools-gen --category=finance; DO NOT EDIT.

//! Generated tools grouped by URL host `twelvedata`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStockDetailArgs {
    pub symbol: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetStockDetailTool {
    base: ToolBase,
}

impl GetStockDetailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStockDetailTool {
    const NAME: &'static str = "get_stock_detail";
    type Args = GetStockDetailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed stock information including open, high, low, close, volume, 52-week range, average volume, market open status, and percent change. Use when the user wants comprehensive stock data.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker symbol. Examples: \"AAPL\", \"TSLA\", \"GOOGL\", \"MSFT\", \"AMZN\", \"NVDA\"." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/quote?symbol={symbol}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStockPriceArgs {
    pub symbol: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetStockPriceTool {
    base: ToolBase,
}

impl GetStockPriceTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStockPriceTool {
    const NAME: &'static str = "get_stock_price";
    type Args = GetStockPriceArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the latest price for a stock. Returns just the current price in USD. Use when the user asks \"how much is AAPL right now\".".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker symbol. Examples: \"AAPL\", \"TSLA\", \"NVDA\"." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/price?symbol={symbol}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStockHistoryArgs {
    pub symbol: String,
    #[serde(default)]
    pub days: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetStockHistoryTool {
    base: ToolBase,
}

impl GetStockHistoryTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStockHistoryTool {
    const NAME: &'static str = "get_stock_history";
    type Args = GetStockHistoryArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get historical daily stock prices (OHLCV). Returns date, open, high, low, close, and volume for recent trading days. Use when the user asks about stock price history or wants to see recent performance.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker symbol. Examples: \"AAPL\", \"TSLA\", \"GOOGL\"." },
                "days": { "type": "integer", "description": "Number of trading days. Default is 7." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/time_series?symbol={symbol}&interval=1day&outputsize={days}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("days", serde_json::json!(7)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchStockArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchStockTool {
    base: ToolBase,
}

impl SearchStockTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchStockTool {
    const NAME: &'static str = "search_stock";
    type Args = SearchStockArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for stocks by ticker symbol or company name. Returns symbol, company name, exchange, currency, and type. Use when the user mentions a company and you need to find its ticker symbol.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search term. Examples: \"Tesla\", \"Apple\", \"NVIDIA\", \"TSLA\", \"AMZN\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/symbol_search?symbol={query}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRsiArgs {
    pub symbol: String,
    #[serde(default)]
    pub interval: Option<String>,
    #[serde(default)]
    pub time_period: Option<i64>,
    #[serde(default)]
    pub outputsize: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetRsiTool {
    base: ToolBase,
}

impl GetRsiTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRsiTool {
    const NAME: &'static str = "get_rsi";
    type Args = GetRsiArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the Relative Strength Index (RSI) technical indicator time series for a stock or crypto symbol. RSI ranges 0-100; above 70 suggests overbought, below 30 oversold. Use for momentum analysis.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker (e.g. \"AAPL\", \"TSLA\", \"NVDA\") or crypto pair with a slash (e.g. \"BTC/USD\", \"ETH/USD\", \"SOL/USD\")." },
                "interval": { "type": "string", "description": "Candle interval: 1min, 5min, 15min, 30min, 45min, 1h, 2h, 4h, 1day, 1week, 1month. Default is \"1day\"." },
                "time_period": { "type": "integer", "description": "Lookback period for the RSI calculation. Default is 14." },
                "outputsize": { "type": "integer", "description": "Number of data points to return. Default is 14." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/rsi?symbol={symbol}&interval={interval}&time_period={time_period}&outputsize={outputsize}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("interval", serde_json::json!("1day")),
                ("time_period", serde_json::json!(14)),
                ("outputsize", serde_json::json!(14)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetMacdArgs {
    pub symbol: String,
    #[serde(default)]
    pub interval: Option<String>,
    #[serde(default)]
    pub outputsize: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetMacdTool {
    base: ToolBase,
}

impl GetMacdTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetMacdTool {
    const NAME: &'static str = "get_macd";
    type Args = GetMacdArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the Moving Average Convergence Divergence (MACD) technical indicator for a stock or crypto symbol. Returns macd, signal, and histogram values (default fast=12, slow=26, signal=9). Use for trend and momentum crossover analysis.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker (e.g. \"AAPL\") or crypto pair with a slash (e.g. \"BTC/USD\")." },
                "interval": { "type": "string", "description": "Candle interval: 1min, 5min, 15min, 30min, 45min, 1h, 2h, 4h, 1day, 1week, 1month. Default is \"1day\"." },
                "outputsize": { "type": "integer", "description": "Number of data points to return. Default is 14." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/macd?symbol={symbol}&interval={interval}&outputsize={outputsize}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("interval", serde_json::json!("1day")),
                ("outputsize", serde_json::json!(14)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSmaArgs {
    pub symbol: String,
    #[serde(default)]
    pub interval: Option<String>,
    #[serde(default)]
    pub time_period: Option<i64>,
    #[serde(default)]
    pub outputsize: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetSmaTool {
    base: ToolBase,
}

impl GetSmaTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSmaTool {
    const NAME: &'static str = "get_sma";
    type Args = GetSmaArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the Simple Moving Average (SMA) technical indicator time series for a stock or crypto symbol. Use for trend analysis and support/resistance levels.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker (e.g. \"AAPL\") or crypto pair with a slash (e.g. \"BTC/USD\")." },
                "interval": { "type": "string", "description": "Candle interval: 1min, 5min, 15min, 30min, 45min, 1h, 2h, 4h, 1day, 1week, 1month. Default is \"1day\"." },
                "time_period": { "type": "integer", "description": "Number of periods to average. Common values 20, 50, 200. Default is 20." },
                "outputsize": { "type": "integer", "description": "Number of data points to return. Default is 14." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/sma?symbol={symbol}&interval={interval}&time_period={time_period}&outputsize={outputsize}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("interval", serde_json::json!("1day")),
                ("time_period", serde_json::json!(20)),
                ("outputsize", serde_json::json!(14)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetEmaArgs {
    pub symbol: String,
    #[serde(default)]
    pub interval: Option<String>,
    #[serde(default)]
    pub time_period: Option<i64>,
    #[serde(default)]
    pub outputsize: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetEmaTool {
    base: ToolBase,
}

impl GetEmaTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetEmaTool {
    const NAME: &'static str = "get_ema";
    type Args = GetEmaArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the Exponential Moving Average (EMA) technical indicator time series for a stock or crypto symbol. EMA weights recent prices more heavily than SMA. Use for trend analysis.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker (e.g. \"AAPL\") or crypto pair with a slash (e.g. \"BTC/USD\")." },
                "interval": { "type": "string", "description": "Candle interval: 1min, 5min, 15min, 30min, 45min, 1h, 2h, 4h, 1day, 1week, 1month. Default is \"1day\"." },
                "time_period": { "type": "integer", "description": "Number of periods for the EMA. Common values 12, 26, 50, 200. Default is 20." },
                "outputsize": { "type": "integer", "description": "Number of data points to return. Default is 14." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/ema?symbol={symbol}&interval={interval}&time_period={time_period}&outputsize={outputsize}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("interval", serde_json::json!("1day")),
                ("time_period", serde_json::json!(20)),
                ("outputsize", serde_json::json!(14)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetBbandsArgs {
    pub symbol: String,
    #[serde(default)]
    pub interval: Option<String>,
    #[serde(default)]
    pub time_period: Option<i64>,
    #[serde(default)]
    pub outputsize: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetBbandsTool {
    base: ToolBase,
}

impl GetBbandsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetBbandsTool {
    const NAME: &'static str = "get_bbands";
    type Args = GetBbandsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get Bollinger Bands (upper, middle, lower) technical indicator time series for a stock or crypto symbol. Bands widen with volatility. Use for volatility and mean-reversion analysis.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "symbol": { "type": "string", "description": "Stock ticker (e.g. \"AAPL\") or crypto pair with a slash (e.g. \"BTC/USD\")." },
                "interval": { "type": "string", "description": "Candle interval: 1min, 5min, 15min, 30min, 45min, 1h, 2h, 4h, 1day, 1week, 1month. Default is \"1day\"." },
                "time_period": { "type": "integer", "description": "Number of periods for the moving average. Default is 20." },
                "outputsize": { "type": "integer", "description": "Number of data points to return. Default is 14." },
            },
            "required": [
                "symbol",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.twelvedata.com/bbands?symbol={symbol}&interval={interval}&time_period={time_period}&outputsize={outputsize}&apikey=$TWELVEDATA_API_KEYS",
            headers: None,
            defaults: Some(Box::new([
                ("interval", serde_json::json!("1day")),
                ("time_period", serde_json::json!(20)),
                ("outputsize", serde_json::json!(14)),
            ])),
        }, map).await
    }
}
