// Code generated by rig-tools-gen --category=food-drink; DO NOT EDIT.

//! Generated tools grouped by URL host `thecocktaildb`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchCocktailArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchCocktailTool {
    base: ToolBase,
}

impl SearchCocktailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchCocktailTool {
    const NAME: &'static str = "search_cocktail";
    type Args = SearchCocktailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for cocktail and drink recipes by name. Returns full recipe with ingredients, measurements, instructions (multi-language), glass type, and category. Use when the user asks for a cocktail recipe or how to make a drink.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Cocktail name to search. Examples: \"margarita\", \"mojito\", \"espresso martini\", \"pina colada\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.thecocktaildb.com/api/json/v1/1/search.php?s={query}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRandomCocktailArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetRandomCocktailTool {
    base: ToolBase,
}

impl GetRandomCocktailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRandomCocktailTool {
    const NAME: &'static str = "get_random_cocktail";
    type Args = GetRandomCocktailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a random cocktail recipe. Returns full recipe with ingredients, measurements, instructions, and drink image. Use when the user wants a random drink idea.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.thecocktaildb.com/api/json/v1/1/random.php",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCocktailsByIngredientArgs {
    pub ingredient: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetCocktailsByIngredientTool {
    base: ToolBase,
}

impl GetCocktailsByIngredientTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCocktailsByIngredientTool {
    const NAME: &'static str = "get_cocktails_by_ingredient";
    type Args = GetCocktailsByIngredientArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Find cocktail recipes that use a specific ingredient. Returns drink name, thumbnail, and ID. Use when the user has a spirit or ingredient and wants drink ideas.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "ingredient": { "type": "string", "description": "Ingredient to filter by. Examples: \"vodka\", \"rum\", \"gin\", \"tequila\", \"lime\"." },
            },
            "required": [
                "ingredient",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl:
                        "https://www.thecocktaildb.com/api/json/v1/1/filter.php?i={ingredient}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
