// Code generated by rig-tools-gen --category=food-drink; DO NOT EDIT.

//! Generated tools grouped by URL host `themealdb`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchRecipeArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchRecipeTool {
    base: ToolBase,
}

impl SearchRecipeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchRecipeTool {
    const NAME: &'static str = "search_recipe";
    type Args = SearchRecipeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for meal recipes by name. Returns full recipe with ingredients, measurements, cooking instructions, category, origin country, and YouTube video link. Use when the user asks for a recipe or how to cook something.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Meal name to search. Examples: \"rendang\", \"pasta\", \"sushi\", \"nasi goreng\", \"curry\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.themealdb.com/api/json/v1/1/search.php?s={query}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRandomRecipeArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetRandomRecipeTool {
    base: ToolBase,
}

impl GetRandomRecipeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRandomRecipeTool {
    const NAME: &'static str = "get_random_recipe";
    type Args = GetRandomRecipeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a random meal recipe from around the world. Returns full recipe with ingredients, measurements, cooking instructions, and YouTube video link. Use when the user wants a random cooking idea or inspiration.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.themealdb.com/api/json/v1/1/random.php",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetRecipesByIngredientArgs {
    pub ingredient: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetRecipesByIngredientTool {
    base: ToolBase,
}

impl GetRecipesByIngredientTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetRecipesByIngredientTool {
    const NAME: &'static str = "get_recipes_by_ingredient";
    type Args = GetRecipesByIngredientArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Find meal recipes that use a specific ingredient. Returns meal name, thumbnail, and ID. Use when the user has an ingredient and wants recipe ideas.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "ingredient": { "type": "string", "description": "Main ingredient to filter by. Examples: \"chicken\", \"salmon\", \"tofu\", \"rice\", \"avocado\"." },
            },
            "required": [
                "ingredient",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.themealdb.com/api/json/v1/1/filter.php?i={ingredient}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ListRecipeCategoriesArgs {}

#[derive(Debug, Clone, Default)]
pub struct ListRecipeCategoriesTool {
    base: ToolBase,
}

impl ListRecipeCategoriesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for ListRecipeCategoriesTool {
    const NAME: &'static str = "list_recipe_categories";
    type Args = ListRecipeCategoriesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "List all available meal categories (e.g. Beef, Chicken, Dessert, Seafood, Vegetarian, etc.). Use when the user wants to browse recipes by category.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://www.themealdb.com/api/json/v1/1/categories.php",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
