// Code generated by rig-tools-gen --category=food-drink; DO NOT EDIT.

//! Generated tools grouped by URL host `world`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetFoodByBarcodeArgs {
    pub barcode: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetFoodByBarcodeTool {
    base: ToolBase,
}

impl GetFoodByBarcodeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetFoodByBarcodeTool {
    const NAME: &'static str = "get_food_by_barcode";
    type Args = GetFoodByBarcodeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Look up a food product by its barcode. Returns product name, brand, ingredients, nutrition facts (calories, fat, sugar, protein, salt), additives, allergens, and Nutri-Score grade. Use when the user scans or provides a barcode and wants to know what's in a food product.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "barcode": { "type": "string", "description": "Product barcode number (EAN/UPC). Examples: \"8886008101053\" (Aqua), \"3017620422003\" (Nutella), \"5000159484695\" (KitKat)." },
            },
            "required": [
                "barcode",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://world.openfoodfacts.org/api/v0/product/{barcode}.json",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchFoodProductsArgs {
    pub query: String,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchFoodProductsTool {
    base: ToolBase,
}

impl SearchFoodProductsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchFoodProductsTool {
    const NAME: &'static str = "search_food_products";
    type Args = SearchFoodProductsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for food products by name or keyword. Returns product name, brand, nutrition grade (Nutri-Score), calories, and ingredients. Use when the user asks about nutritional info of a food or wants to compare products.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search terms. Examples: \"nutella\", \"oat milk\", \"protein bar\", \"instant noodles\"." },
                "limit": { "type": "integer", "description": "Number of results. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://world.openfoodfacts.org/cgi/search.pl?search_terms={query}&json=1&page_size={limit}",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}
