// Code generated by rig-tools-gen --category=utility; DO NOT EDIT.

//! Generated tools grouped by URL host `chucknorris`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetChuckNorrisJokeArgs {
    #[serde(default)]
    pub category: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetChuckNorrisJokeTool {
    base: ToolBase,
}

impl GetChuckNorrisJokeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetChuckNorrisJokeTool {
    const NAME: &'static str = "get_chuck_norris_joke";
    type Args = GetChuckNorrisJokeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a random Chuck Norris joke. Can filter by category. Categories include: dev, animal, career, celebrity, food, history, money, movie, music, science, sport, travel. Use when the user wants a funny Chuck Norris joke.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "category": { "type": "string", "description": "Joke category. Options: \"dev\", \"animal\", \"career\", \"celebrity\", \"food\", \"history\", \"money\", \"movie\", \"music\", \"science\", \"sport\", \"travel\". Optional." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.chucknorris.io/jokes/random?category={category}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
