// Code generated by rig-tools-gen --category=utility; DO NOT EDIT.

//! Generated tools grouped by URL host `deckofcardsapi`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct NewDeckArgs {}

#[derive(Debug, Clone, Default)]
pub struct NewDeckTool {
    base: ToolBase,
}

impl NewDeckTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for NewDeckTool {
    const NAME: &'static str = "new_deck";
    type Args = NewDeckArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Create a new shuffled deck of cards. Returns deck ID for drawing cards. Use when the user wants to play card games or needs a deck of cards.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DrawCardsArgs {
    pub deck_id: String,
    #[serde(default)]
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct DrawCardsTool {
    base: ToolBase,
}

impl DrawCardsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for DrawCardsTool {
    const NAME: &'static str = "draw_cards";
    type Args = DrawCardsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Draw cards from a deck. Returns card images, values, and suits. Use when the user wants to draw cards from a deck.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "deck_id": { "type": "string", "description": "Deck ID from new_deck. Example: 3p40paa87x90" },
                "count": { "type": "integer", "description": "Number of cards to draw (1-52). Default is 1." },
            },
            "required": [
                "deck_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://deckofcardsapi.com/api/deck/{deck_id}/draw/?count={count}",
                    headers: None,
                    defaults: Some(Box::new([("count", serde_json::json!(1))])),
                },
                map,
            )
            .await
    }
}
