// Code generated by rig-tools-gen --category=utility; DO NOT EDIT.

//! Generated tools grouped by URL host `disify`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ValidateEmailArgs {
    pub email: String,
}

#[derive(Debug, Clone, Default)]
pub struct ValidateEmailTool {
    base: ToolBase,
}

impl ValidateEmailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for ValidateEmailTool {
    const NAME: &'static str = "validate_email";
    type Args = ValidateEmailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Validate an email address and check if it is disposable/temporary, has valid DNS/MX records, is a free provider, or is a role-based email. Returns format validity, disposable detection, DNS status, and confidence score. Use when the user wants to verify if an email is legitimate or check if it's a throwaway/temporary email.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "email": { "type": "string", "description": "Email address to validate. Examples: \"user@gmail.com\", \"test@guerrillamail.com\"." },
            },
            "required": [
                "email",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://disify.com/api/email/{email}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
