// Code generated by rig-tools-gen --category=utility; DO NOT EDIT.

//! Generated tools grouped by URL host `opentdb`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTriviaCategoriesArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetTriviaCategoriesTool {
    base: ToolBase,
}

impl GetTriviaCategoriesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTriviaCategoriesTool {
    const NAME: &'static str = "get_trivia_categories";
    type Args = GetTriviaCategoriesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get all available trivia categories from the Open Trivia Database. Categories include General Knowledge, Film, Music, Science, Sports, History, and more.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://opentdb.com/api_category.php",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTriviaQuestionsArgs {
    #[serde(default)]
    pub amount: Option<i64>,
    #[serde(default)]
    pub category: Option<i64>,
    #[serde(default)]
    pub difficulty: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTriviaQuestionsTool {
    base: ToolBase,
}

impl GetTriviaQuestionsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTriviaQuestionsTool {
    const NAME: &'static str = "get_trivia_questions";
    type Args = GetTriviaQuestionsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get trivia questions by category and difficulty. Returns multiple choice or true/false questions with correct answer. Use when the user wants to play trivia.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "amount": { "type": "integer", "description": "Number of questions (1-50). Default is 5." },
                "category": { "type": "integer", "description": "Category number. Examples: 9 (General Knowledge), 11 (Film), 15 (Video Games), 17 (Science), 18 (Computers), 21 (Sports), 22 (Geography), 23 (History)." },
                "difficulty": { "type": "string", "description": "Difficulty: \"easy\", \"medium\", \"hard\". Optional." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://opentdb.com/api.php?amount={amount}&category={category}&difficulty={difficulty}",
            headers: None,
            defaults: Some(Box::new([
                ("amount", serde_json::json!(5)),
            ])),
        }, map).await
    }
}
