// Code generated by rig-tools-gen --category=utility; DO NOT EDIT.

//! Generated tools grouped by URL host `swapi`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchStarWarsPeopleArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct SearchStarWarsPeopleTool {
    base: ToolBase,
}

impl SearchStarWarsPeopleTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchStarWarsPeopleTool {
    const NAME: &'static str = "search_star_wars_people";
    type Args = SearchStarWarsPeopleArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for Star Wars characters by name. Returns name, height, mass, hair/eye color, birth year, gender, homeworld, and films. Use when the user asks about Star Wars characters.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Character name. Examples: \"Luke Skywalker\", \"Darth Vader\", \"Yoda\", \"Leia\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://swapi.py4e.com/api/people/?search={query}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStarWarsFilmsArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetStarWarsFilmsTool {
    base: ToolBase,
}

impl GetStarWarsFilmsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStarWarsFilmsTool {
    const NAME: &'static str = "get_star_wars_films";
    type Args = GetStarWarsFilmsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get information about all Star Wars films. Returns title, episode ID, director, producer, release date, and opening crawl. Use when the user asks about Star Wars movies.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://swapi.py4e.com/api/films/",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetStarWarsPlanetArgs {
    pub planet_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetStarWarsPlanetTool {
    base: ToolBase,
}

impl GetStarWarsPlanetTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetStarWarsPlanetTool {
    const NAME: &'static str = "get_star_wars_planet";
    type Args = GetStarWarsPlanetArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get information about a Star Wars planet by ID. Returns name, climate, terrain, population, gravity, and orbital period.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "planet_id": { "type": "string", "description": "Planet ID. Examples: 1 (Tatooine), 2 (Alderaan), 3 (Yavin IV), 4 (Hoth)." },
            },
            "required": [
                "planet_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://swapi.py4e.com/api/planets/{planet_id}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
