// Code generated by rig-tools-gen --category=utility; DO NOT EDIT.

//! Generated tools grouped by URL host `v2`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetJokeArgs {
    #[serde(default)]
    pub category: Option<String>,
    #[serde(default)]
    #[serde(rename = "type")]
    pub r#type: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetJokeTool {
    base: ToolBase,
}

impl GetJokeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetJokeTool {
    const NAME: &'static str = "get_joke";
    type Args = GetJokeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a random joke. Can filter by category. Supports single-line jokes and two-part (setup + delivery) jokes. Categories: Programming, Misc, Dark, Pun, Spooky, Christmas. Use when the user asks for a joke or wants something funny.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "category": { "type": "string", "description": "Joke category. Options: \"Any\" (default), \"Programming\", \"Misc\", \"Dark\", \"Pun\", \"Spooky\", \"Christmas\". Multiple categories separated by comma: \"Programming,Pun\"." },
                "type": { "type": "string", "description": "Joke type. Options: \"single\" (one-liner), \"twopart\" (setup + delivery). Default is \"single\"." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://v2.jokeapi.dev/joke/{category}?type={type}&safe-mode",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
