// Code generated by rig-tools-gen --category=news-media; DO NOT EDIT.

//! Generated tools grouped by URL host `hacker_news`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTopNewsArgs {
    #[serde(default)]
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTopNewsTool {
    base: ToolBase,
}

impl GetTopNewsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTopNewsTool {
    const NAME: &'static str = "get_top_news";
    type Args = GetTopNewsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the current top story IDs from Hacker News. Use when the user asks about trending tech news or what's popular on HN.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "count": { "type": "integer", "description": "Number of top stories to retrieve. Default is 5." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://hacker-news.firebaseio.com/v0/topstories.json?limitToFirst={count}&orderBy=\"$key\"",
            headers: None,
            defaults: Some(Box::new([
                ("count", serde_json::json!(5)),
            ])),
        }, map).await
    }
}
