// Code generated by rig-tools-gen --category=news-media; DO NOT EDIT.

//! Generated tools grouped by URL host `newsapi`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTopHeadlinesArgs {
    #[serde(default)]
    pub country: Option<String>,
    #[serde(default)]
    pub category: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTopHeadlinesTool {
    base: ToolBase,
}

impl GetTopHeadlinesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTopHeadlinesTool {
    const NAME: &'static str = "get_top_headlines";
    type Args = GetTopHeadlinesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get breaking news headlines for a country and/or category. Returns article title, source, author, description, URL, image, and publication date. Use when the user asks about current news, breaking news, or top headlines.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "country": { "type": "string", "description": "Two-letter ISO 3166-1 country code. Examples: us, gb, id, de, jp, fr, au, br. Default is \"us\"." },
                "category": { "type": "string", "description": "News category: \"business\", \"entertainment\", \"general\", \"health\", \"science\", \"sports\", \"technology\". Optional." },
                "limit": { "type": "integer", "description": "Number of articles. Default is 5." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://newsapi.org/v2/top-headlines?country={country}&category={category}&pageSize={limit}&apiKey=ba62a43a4f1b4e019acec21ebef9b710",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SearchNewsArgs {
    pub query: String,
    #[serde(default)]
    pub sort_by: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct SearchNewsTool {
    base: ToolBase,
}

impl SearchNewsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for SearchNewsTool {
    const NAME: &'static str = "search_news";
    type Args = SearchNewsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Search for news articles by keyword across thousands of sources worldwide. Returns article title, source, author, description, URL, image, and publication date. Use when the user asks to find news about a specific topic, event, or person.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Search keywords. Examples: \"artificial intelligence\", \"Indonesia election\", \"climate change\", \"Tesla\", \"World Cup\"." },
                "sort_by": { "type": "string", "description": "Sort order: \"relevancy\" (default), \"popularity\", \"publishedAt\" (newest first). Optional." },
                "limit": { "type": "integer", "description": "Number of articles. Default is 5." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://newsapi.org/v2/everything?q={query}&sortBy={sort_by}&pageSize={limit}&apiKey=ba62a43a4f1b4e019acec21ebef9b710",
            headers: None,
            defaults: Some(Box::new([
                ("limit", serde_json::json!(5)),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetNewsSourcesArgs {
    #[serde(default)]
    pub category: Option<String>,
    #[serde(default)]
    pub country: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetNewsSourcesTool {
    base: ToolBase,
}

impl GetNewsSourcesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetNewsSourcesTool {
    const NAME: &'static str = "get_news_sources";
    type Args = GetNewsSourcesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get available news sources. Returns source name, description, URL, category, language, and country. Use when the user asks what news sources are available or wants to know about a specific news outlet.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "category": { "type": "string", "description": "Filter by category: \"business\", \"entertainment\", \"general\", \"health\", \"science\", \"sports\", \"technology\". Optional." },
                "country": { "type": "string", "description": "Filter by country code. Examples: us, gb, id. Optional." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://newsapi.org/v2/top-headlines/sources?category={category}&country={country}&apiKey=ba62a43a4f1b4e019acec21ebef9b710",
            headers: None,
            defaults: None,
        }, map).await
    }
}
