// Code generated by rig-tools-gen --category=gaming; DO NOT EDIT.

//! Generated tools grouped by URL host `pokeapi`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetPokemonArgs {
    pub pokemon: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetPokemonTool {
    base: ToolBase,
}

impl GetPokemonTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetPokemonTool {
    const NAME: &'static str = "get_pokemon";
    type Args = GetPokemonArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a Pokémon by name or ID. Returns abilities, types, height, weight, base stats, moves, sprites, and species information. Use when the user asks about a specific Pokémon.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "pokemon": { "type": "string", "description": "Pokémon name or National Pokédex ID. Examples: \"pikachu\", \"charizard\", \"mewtwo\", \"25\"." },
            },
            "required": [
                "pokemon",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://pokeapi.co/api/v2/pokemon/{pokemon}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetPokemonSpeciesArgs {
    pub pokemon: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetPokemonSpeciesTool {
    base: ToolBase,
}

impl GetPokemonSpeciesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetPokemonSpeciesTool {
    const NAME: &'static str = "get_pokemon_species";
    type Args = GetPokemonSpeciesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get Pokémon species data including flavor text, habitat, generation, growth rate, evolution chain URL, and capture rate. Use when the user wants Pokédex descriptions.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "pokemon": { "type": "string", "description": "Pokémon species name or National Pokédex ID. Examples: \"pikachu\", \"eevee\", \"bulbasaur\", \"133\"." },
            },
            "required": [
                "pokemon",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://pokeapi.co/api/v2/pokemon-species/{pokemon}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetPokemonTypeArgs {
    pub type_name: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetPokemonTypeTool {
    base: ToolBase,
}

impl GetPokemonTypeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetPokemonTypeTool {
    const NAME: &'static str = "get_pokemon_type";
    type Args = GetPokemonTypeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get information about a Pokémon type including damage relations, moves, and Pokémon that have this type. Use when the user asks about type matchups or weaknesses.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "type_name": { "type": "string", "description": "Pokémon type name. Examples: \"fire\", \"water\", \"electric\", \"grass\", \"psychic\", \"dragon\"." },
            },
            "required": [
                "type_name",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://pokeapi.co/api/v2/type/{type_name}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
