// Code generated by rig-tools-gen --category=religion; DO NOT EDIT.

//! Generated tools grouped by URL host `alquran`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetQuranSurahArgs {
    pub surah_number: i64,
    #[serde(default)]
    pub edition: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetQuranSurahTool {
    base: ToolBase,
}

impl GetQuranSurahTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetQuranSurahTool {
    const NAME: &'static str = "get_quran_surah";
    type Args = GetQuranSurahArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get all ayahs (verses) of a specific surah from the Quran. Returns Arabic text by default, or a translation in the specified language. Supports Indonesian (id.indonesian), English (en.sahih, en.pickthall), and many other translations. Use when the user asks to read a Quran surah or wants the text of a specific surah.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "surah_number": { "type": "integer", "description": "Surah number (1-114). Examples: 1 (Al-Fatihah), 2 (Al-Baqarah), 36 (Ya-Sin), 55 (Ar-Rahman), 112 (Al-Ikhlas)." },
                "edition": { "type": "string", "description": "Quran edition/translation. \"quran-uthmani\" for Arabic (default), \"id.indonesian\" for Bahasa Indonesia, \"en.sahih\" for English Sahih International, \"en.pickthall\" for English Pickthall. Optional." },
            },
            "required": [
                "surah_number",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.alquran.cloud/v1/surah/{surah_number}/{edition}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetQuranAyahArgs {
    pub ayah_number: i64,
    #[serde(default)]
    pub edition: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetQuranAyahTool {
    base: ToolBase,
}

impl GetQuranAyahTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetQuranAyahTool {
    const NAME: &'static str = "get_quran_ayah";
    type Args = GetQuranAyahArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get a specific ayah (verse) from the Quran by its absolute number (1-6236) or by surah:ayah format. Returns Arabic text by default or translation in specified language. Use when the user asks for a specific Quran verse.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "ayah_number": { "type": "integer", "description": "Absolute ayah number (1-6236). Example: 1 (Al-Fatihah 1:1), 262 (Al-Baqarah 2:255, Ayatul Kursi)." },
                "edition": { "type": "string", "description": "Quran edition/translation. \"quran-uthmani\" for Arabic (default), \"id.indonesian\" for Bahasa Indonesia, \"en.sahih\" for English. Optional." },
            },
            "required": [
                "ayah_number",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.alquran.cloud/v1/ayah/{ayah_number}/{edition}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetQuranJuzArgs {
    pub juz_number: i64,
    #[serde(default)]
    pub edition: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetQuranJuzTool {
    base: ToolBase,
}

impl GetQuranJuzTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetQuranJuzTool {
    const NAME: &'static str = "get_quran_juz";
    type Args = GetQuranJuzArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get all ayahs in a specific Juz (para) of the Quran. The Quran has 30 Juz. Use when the user wants to read a specific Juz.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "juz_number": { "type": "integer", "description": "Juz number (1-30)." },
                "edition": { "type": "string", "description": "Quran edition/translation. Optional. Default is Arabic." },
            },
            "required": [
                "juz_number",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.alquran.cloud/v1/juz/{juz_number}/{edition}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
