// Code generated by rig-tools-gen --category=religion; DO NOT EDIT.

//! Generated tools grouped by URL host `bible_api`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetBibleVerseArgs {
    pub reference: String,
    #[serde(default)]
    pub translation: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetBibleVerseTool {
    base: ToolBase,
}

impl GetBibleVerseTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetBibleVerseTool {
    const NAME: &'static str = "get_bible_verse";
    type Args = GetBibleVerseArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Look up a Bible verse or passage by book, chapter, and verse reference. Returns the verse text, book name, chapter, verse number, and translation info. Supports multiple translations. Use when the user asks for a Bible verse or passage.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "reference": { "type": "string", "description": "Bible reference in standard format. Examples: \"John 3:16\", \"Psalm 23:1-6\", \"Genesis 1:1\", \"Romans 8:28\", \"Matthew 5:3-12\"." },
                "translation": { "type": "string", "description": "Bible translation. Available: \"web\" (World English Bible, default), \"kjv\" (King James Version), \"bbe\" (Bible in Basic English), \"webbe\", \"alabama\", \"clementine\", \"chamorro\", \"daretqad\", \"kozhiba\", \"mateo\", \"miami\", \"navajo\", \"nuosu\", \"pohnpei\", \"western\", \"chinese\". Optional." },
            },
            "required": [
                "reference",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://bible-api.com/{reference}?translation={translation}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
