// Code generated by rig-tools-gen --category=religion; DO NOT EDIT.

//! Generated tools grouped by URL host `wikimedia`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetOnThisDayArgs {
    pub month: i64,
    pub day: i64,
}

#[derive(Debug, Clone, Default)]
pub struct GetOnThisDayTool {
    base: ToolBase,
}

impl GetOnThisDayTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetOnThisDayTool {
    const NAME: &'static str = "get_on_this_day";
    type Args = GetOnThisDayArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get historical events, births, deaths, and holidays that happened on a specific date. Returns short descriptions with Wikipedia links. Use when the user asks \"what happened on this day?\" or wants historical trivia.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "month": { "type": "integer", "description": "Month number (1-12)." },
                "day": { "type": "integer", "description": "Day number (1-31)." },
            },
            "required": [
                "month",
                "day",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.wikimedia.org/feed/v1/wikipedia/en/onthisday/all/{month}/{day}",
            headers: None,
            defaults: None,
        }, map).await
    }
}
