// Code generated by rig-tools-gen --category=sports; DO NOT EDIT.

//! Generated tools grouped by URL host `football_data`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCompetitionsArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetCompetitionsTool {
    base: ToolBase,
}

impl GetCompetitionsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCompetitionsTool {
    const NAME: &'static str = "get_competitions";
    type Args = GetCompetitionsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "List all available football competitions (leagues, cups, tournaments) including Premier League, La Liga, Bundesliga, Serie A, Ligue 1, Champions League, World Cup, and more. Use when the user asks what football competitions or leagues are available.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.football-data.org/v4/competitions/",
                    headers: Some(Box::new([(
                        "X-Auth-Token",
                        "d38185cb115c421c95b69179df3fbf54",
                    )])),
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCompetitionStandingsArgs {
    pub competition_code: String,
    #[serde(default)]
    pub season: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCompetitionStandingsTool {
    base: ToolBase,
}

impl GetCompetitionStandingsTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCompetitionStandingsTool {
    const NAME: &'static str = "get_competition_standings";
    type Args = GetCompetitionStandingsArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the current league standings (table) for a specific football competition. Shows team positions, points, wins, draws, losses, goals for/against, and form. Use when the user asks about league tables, standings, or rankings.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "competition_code": { "type": "string", "description": "Competition code. Common codes: PL (Premier League), BL1 (Bundesliga), SA (Serie A), PD (La Liga), FL1 (Ligue 1), CL (Champions League), ELC (Championship), DED (Eredivisie), PPL (Primeira Liga), SPL (Scottish Prem)." },
                "season": { "type": "string", "description": "Season year (starting year). Example: 2024 for 2024/2025 season. Optional." },
            },
            "required": [
                "competition_code",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.football-data.org/v4/competitions/{competition_code}/standings?season={season}",
            headers: Some(Box::new([
                ("X-Auth-Token", "d38185cb115c421c95b69179df3fbf54"),
            ])),
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCompetitionMatchesArgs {
    pub competition_code: String,
    #[serde(default)]
    pub matchday: Option<String>,
    #[serde(default)]
    pub date_from: Option<String>,
    #[serde(default)]
    pub date_to: Option<String>,
    #[serde(default)]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCompetitionMatchesTool {
    base: ToolBase,
}

impl GetCompetitionMatchesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCompetitionMatchesTool {
    const NAME: &'static str = "get_competition_matches";
    type Args = GetCompetitionMatchesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get matches for a specific football competition. Can filter by matchday, date range, or status. Returns match details including teams, scores, goals, and status (FINISHED, TIMED, IN_PROGRESS). Use when the user asks about upcoming matches, recent results, or fixtures.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "competition_code": { "type": "string", "description": "Competition code. Common codes: PL, BL1, SA, PD, FL1, CL, WC, ELC, DED, PPL, SPL." },
                "matchday": { "type": "string", "description": "Specific matchday number. Example: 10, 34. Optional." },
                "date_from": { "type": "string", "description": "Start date filter (YYYY-MM-DD). Example: 2025-01-01. Optional." },
                "date_to": { "type": "string", "description": "End date filter (YYYY-MM-DD). Example: 2025-01-31. Optional." },
                "status": { "type": "string", "description": "Match status filter. Examples: FINISHED, TIMED, IN_PROGRESS, POSTPONED. Optional." },
            },
            "required": [
                "competition_code",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.football-data.org/v4/competitions/{competition_code}/matches?matchday={matchday}&dateFrom={date_from}&dateTo={date_to}&status={status}",
            headers: Some(Box::new([
                ("X-Auth-Token", "d38185cb115c421c95b69179df3fbf54"),
            ])),
            defaults: None,
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetCompetitionScorersArgs {
    pub competition_code: String,
    #[serde(default)]
    pub limit: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetCompetitionScorersTool {
    base: ToolBase,
}

impl GetCompetitionScorersTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetCompetitionScorersTool {
    const NAME: &'static str = "get_competition_scorers";
    type Args = GetCompetitionScorersArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the top scorers for a specific football competition. Returns player names, teams, goals scored, assists, and penalties. Use when the user asks about top scorers, golden boot, or leading goal scorers.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "competition_code": { "type": "string", "description": "Competition code. Common codes: PL, BL1, SA, PD, FL1, CL." },
                "limit": { "type": "string", "description": "Number of top scorers to return. Default is 10." },
            },
            "required": [
                "competition_code",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.football-data.org/v4/competitions/{competition_code}/scorers?limit={limit}",
            headers: Some(Box::new([
                ("X-Auth-Token", "d38185cb115c421c95b69179df3fbf54"),
            ])),
            defaults: Some(Box::new([
                ("limit", serde_json::json!("10")),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTeamInfoArgs {
    pub team_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetTeamInfoTool {
    base: ToolBase,
}

impl GetTeamInfoTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTeamInfoTool {
    const NAME: &'static str = "get_team_info";
    type Args = GetTeamInfoArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a football team including squad, coach, founded year, venue, club colors, and running competitions. Use when the user asks about a specific team.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "team_id": { "type": "string", "description": "Team ID. Common IDs: 66 (Man United), 65 (Man City), 64 (Liverpool), 57 (Arsenal), 61 (Chelsea), 73 (Tottenham), 5 (Bayern Munich), 81 (Barcelona), 86 (Real Madrid), 109 (Juventus), 108 (Inter), 110 (Lazio), 113 (Napoli)." },
            },
            "required": [
                "team_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.football-data.org/v4/teams/{team_id}",
                    headers: Some(Box::new([(
                        "X-Auth-Token",
                        "d38185cb115c421c95b69179df3fbf54",
                    )])),
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTeamMatchesArgs {
    pub team_id: String,
    #[serde(default)]
    pub date_from: Option<String>,
    #[serde(default)]
    pub date_to: Option<String>,
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub limit: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetTeamMatchesTool {
    base: ToolBase,
}

impl GetTeamMatchesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTeamMatchesTool {
    const NAME: &'static str = "get_team_matches";
    type Args = GetTeamMatchesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get upcoming and recent matches for a specific football team. Can filter by date range, competition, or status. Use when the user asks about a team's schedule, fixtures, or recent results.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "team_id": { "type": "string", "description": "Team ID. Common IDs: 66 (Man United), 65 (Man City), 64 (Liverpool), 57 (Arsenal), 61 (Chelsea), 73 (Tottenham), 5 (Bayern Munich), 81 (Barcelona), 86 (Real Madrid)." },
                "date_from": { "type": "string", "description": "Start date filter (YYYY-MM-DD). Optional." },
                "date_to": { "type": "string", "description": "End date filter (YYYY-MM-DD). Optional." },
                "status": { "type": "string", "description": "Match status filter. Examples: FINISHED, TIMED. Optional." },
                "limit": { "type": "string", "description": "Number of matches to return. Default is 10. Optional." },
            },
            "required": [
                "team_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.football-data.org/v4/teams/{team_id}/matches?dateFrom={date_from}&dateTo={date_to}&status={status}&limit={limit}",
            headers: Some(Box::new([
                ("X-Auth-Token", "d38185cb115c421c95b69179df3fbf54"),
            ])),
            defaults: Some(Box::new([
                ("limit", serde_json::json!("10")),
            ])),
        }, map).await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetMatchDetailArgs {
    pub match_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetMatchDetailTool {
    base: ToolBase,
}

impl GetMatchDetailTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetMatchDetailTool {
    const NAME: &'static str = "get_match_detail";
    type Args = GetMatchDetailArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed information about a specific football match including lineups, goals, bookings, substitutions, score, head-to-head stats, and odds. Use when the user asks about a specific match result or details.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "match_id": { "type": "string", "description": "The unique match ID. Obtained from competition or team match listings." },
            },
            "required": [
                "match_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.football-data.org/v4/matches/{match_id}",
                    headers: Some(Box::new([(
                        "X-Auth-Token",
                        "d38185cb115c421c95b69179df3fbf54",
                    )])),
                    defaults: None,
                },
                map,
            )
            .await
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetPersonInfoArgs {
    pub person_id: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetPersonInfoTool {
    base: ToolBase,
}

impl GetPersonInfoTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetPersonInfoTool {
    const NAME: &'static str = "get_person_info";
    type Args = GetPersonInfoArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get information about a football player or coach including name, date of birth, nationality, position, current team, and contract details. Use when the user asks about a specific player or coach.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "person_id": { "type": "string", "description": "Person ID. Example: 44 (Cristiano Ronaldo), 278 (Lionel Messi). IDs are obtained from match or squad listings." },
            },
            "required": [
                "person_id",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.football-data.org/v4/persons/{person_id}",
                    headers: Some(Box::new([(
                        "X-Auth-Token",
                        "d38185cb115c421c95b69179df3fbf54",
                    )])),
                    defaults: None,
                },
                map,
            )
            .await
    }
}
