// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `ipwho`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetIpLocationArgs {
    #[serde(default)]
    pub ip_address: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GetIpLocationTool {
    base: ToolBase,
}

impl GetIpLocationTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetIpLocationTool {
    const NAME: &'static str = "get_ip_location";
    type Args = GetIpLocationArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get geolocation data for an IP address. Returns country, region, city, latitude, longitude, ISP, timezone, postal code, calling code, and country flag. Use when the user asks about the location of an IP address or wants to know their own IP location.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "ip_address": { "type": "string", "description": "IPv4 or IPv6 address. Examples: \"8.8.8.8\", \"1.1.1.1\". Leave empty to look up the caller's own IP." },
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://ipwho.is/{ip_address}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
