// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `nominatim`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GeocodeArgs {
    pub query: String,
}

#[derive(Debug, Clone, Default)]
pub struct GeocodeTool {
    base: ToolBase,
}

impl GeocodeTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GeocodeTool {
    const NAME: &'static str = "geocode";
    type Args = GeocodeArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Convert a place name or address into geographic coordinates (latitude and longitude). Use when the user needs coordinates for a city, address, or landmark.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "Place name, address, or landmark. Examples: \"Paris\", \"Eiffel Tower\", \"Jakarta\"." },
            },
            "required": [
                "query",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl:
                        "https://nominatim.openstreetmap.org/search?q={query}&format=json&limit=1",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
