// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `open_meteo`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetWeatherForecastArgs {
    pub latitude: f64,
    pub longitude: f64,
    #[serde(default)]
    pub days: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct GetWeatherForecastTool {
    base: ToolBase,
}

impl GetWeatherForecastTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetWeatherForecastTool {
    const NAME: &'static str = "get_weather_forecast";
    type Args = GetWeatherForecastArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get detailed weather forecast for a location by coordinates. Returns daily max/min temperature and precipitation for up to 16 days. More detailed than wttr.in. Use when the user wants a multi-day weather forecast.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "latitude": { "type": "number", "description": "Latitude. Examples: -6.2088 (Jakarta), 40.7128 (New York)." },
                "longitude": { "type": "number", "description": "Longitude. Examples: 106.8456 (Jakarta), -74.0060 (New York)." },
                "days": { "type": "integer", "description": "Number of forecast days (1-16). Default is 7." },
            },
            "required": [
                "latitude",
                "longitude",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base.exec(&RequestSpec {
            method: "GET",
            url_tpl: "https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode,windspeed_10m_max&timezone=auto&forecast_days={days}",
            headers: None,
            defaults: Some(Box::new([
                ("days", serde_json::json!(7)),
            ])),
        }, map).await
    }
}
