// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `sunrisesunset`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetSunTimesArgs {
    pub latitude: f64,
    pub longitude: f64,
}

#[derive(Debug, Clone, Default)]
pub struct GetSunTimesTool {
    base: ToolBase,
}

impl GetSunTimesTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetSunTimesTool {
    const NAME: &'static str = "get_sun_times";
    type Args = GetSunTimesArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get sunrise, sunset, dawn, dusk, and day length for a location. Use when the user asks about sunrise/sunset times or daylight hours.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "latitude": { "type": "number", "description": "Latitude. Examples: -6.2088 (Jakarta), 40.7128 (New York)." },
                "longitude": { "type": "number", "description": "Longitude. Examples: 106.8456 (Jakarta), -74.0060 (New York)." },
            },
            "required": [
                "latitude",
                "longitude",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.sunrisesunset.io/json?lat={latitude}&lng={longitude}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
