// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `timeapi`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetTimeInTimezoneArgs {
    pub timezone: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetTimeInTimezoneTool {
    base: ToolBase,
}

impl GetTimeInTimezoneTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetTimeInTimezoneTool {
    const NAME: &'static str = "get_time_in_timezone";
    type Args = GetTimeInTimezoneArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the current date and time in a specific timezone. Returns year, month, day, hour, minute, seconds, day of week, and DST status. Use when the user asks \"what time is it in Tokyo?\" or needs timezone info.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "timezone": { "type": "string", "description": "IANA timezone name. Examples: \"Asia/Jakarta\", \"America/New_York\", \"Europe/London\", \"Asia/Tokyo\", \"Australia/Sydney\", \"America/Los_Angeles\"." },
            },
            "required": [
                "timezone",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://timeapi.io/api/time/current/zone?timeZone={timezone}",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
