// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `wheretheiss`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetIssPositionArgs {}

#[derive(Debug, Clone, Default)]
pub struct GetIssPositionTool {
    base: ToolBase,
}

impl GetIssPositionTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetIssPositionTool {
    const NAME: &'static str = "get_iss_position";
    type Args = GetIssPositionArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get the real-time position of the International Space Station. Returns latitude, longitude, altitude (km), velocity (km/h), and visibility (daylight/eclipsed). Use when the user asks where the ISS is right now or about its current location.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
            },
            "required": []
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://api.wheretheiss.at/v1/satellites/25544",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
