// Code generated by rig-tools-gen --category=weather-geo; DO NOT EDIT.

//! Generated tools grouped by URL host `wttr`.

use crate::httpclient::{RequestSpec, ToolBase, ToolOptions};
use rig::tool::PortableTool;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GetWeatherArgs {
    pub location: String,
}

#[derive(Debug, Clone, Default)]
pub struct GetWeatherTool {
    base: ToolBase,
}

impl GetWeatherTool {
    pub fn new(opts: ToolOptions) -> Self {
        Self {
            base: ToolBase::new(opts),
        }
    }
}

impl PortableTool for GetWeatherTool {
    const NAME: &'static str = "get_weather";
    type Args = GetWeatherArgs;
    type Output = String;
    type Error = crate::httpclient::ToolError;

    fn description(&self) -> String {
        "Get current weather conditions for a city including temperature, humidity, wind speed, and weather description. Use when the user asks about the weather or conditions in any location.".into()
    }

    fn parameters(&self) -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "location": { "type": "string", "description": "City name for the weather query. Can include country for disambiguation. Examples: \"Paris\", \"Jakarta\", \"New York\", \"Tokyo\"." },
            },
            "required": [
                "location",
            ]
        })
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        let mut map = serde_json::to_value(&args)
            .map_err(crate::httpclient::ToolError::json)?
            .as_object()
            .cloned()
            .unwrap_or_default();
        // Drop null-valued keys so Option::None fields don't pollute the URL.
        map.retain(|_, v| !v.is_null());
        self.base
            .exec(
                &RequestSpec {
                    method: "GET",
                    url_tpl: "https://wttr.in/{location}?format=j1",
                    headers: None,
                    defaults: None,
                },
                map,
            )
            .await
    }
}
